// Fixtures for the formats shown through LibreOffice (0.3.0). OpenDocument files, RTF and TIFF are written here,
// independently of LibreOffice. The older binary formats (.doc .xls .ppt) have no independent producer available, so
// scripts/make-legacy-office.ps1 converts this corpus's own Word, Excel and PowerPoint fixtures with LibreOffice once;
// they prove the safety checks and behaviour, not rendering fidelity. They are recorded here and kept in git.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import JSZip from "jszip";
import { CORPUS, LISTENER, WEBDAV_UNC, SAFE_RULES, FIXED_DATE, png, record, write } from "./lib.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const licence = "Generated by this repository; no third-party content";
const own = "generator (hand-written XML, packaged with JSZip)";
const rec = (file, format, category, expect, producer = own, extra = {}) =>
  record({ id: `converted-${file.replace(/[/.]/g, "-")}`, file, format, category, producer, licence, expect, rules: SAFE_RULES, ...extra });

const NS = 'xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" ' +
  'xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0" xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" ' +
  'xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" ' +
  'xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0" xmlns:xlink="http://www.w3.org/1999/xlink" ' +
  'xmlns:presentation="urn:oasis:names:tc:opendocument:xmlns:presentation:1.0" xmlns:script="urn:oasis:names:tc:opendocument:xmlns:script:1.0" ' +
  'xmlns:of="urn:oasis:names:tc:opendocument:xmlns:of:1.2" office:version="1.3"';
const MIME = { odt: "application/vnd.oasis.opendocument.text", ods: "application/vnd.oasis.opendocument.spreadsheet", odp: "application/vnd.oasis.opendocument.presentation" };

async function odf(kind, body, { styles = "", extra = {}, manifestExtra = "" } = {}) {
  const zip = new JSZip();
  const options = { date: FIXED_DATE };
  zip.file("mimetype", MIME[kind], { ...options, compression: "STORE" });
  zip.file("META-INF/manifest.xml", `<?xml version="1.0" encoding="UTF-8"?><manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.3">` +
    `<manifest:file-entry manifest:full-path="/" manifest:media-type="${MIME[kind]}"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/>${manifestExtra}</manifest:manifest>`, options);
  zip.file("content.xml", `<?xml version="1.0" encoding="UTF-8"?><office:document-content ${NS}><office:automatic-styles>${styles}</office:automatic-styles><office:body>${body}</office:body></office:document-content>`, options);
  for (const [name, content] of Object.entries(extra)) zip.file(name, content, options);
  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
}

const p = text => `<text:p>${text}</text:p>`;
const cell = (value, formula) => typeof value === "number"
  ? `<table:table-cell office:value-type="float" office:value="${value}"${formula ? ` table:formula="${formula}"` : ""}><text:p>${value}</text:p></table:table-cell>`
  : `<table:table-cell office:value-type="string"><text:p>${value}</text:p></table:table-cell>`;
const slide = (name, title, lines = []) =>
  `<draw:page draw:name="${name}"><draw:frame svg:x="2cm" svg:y="2cm" svg:width="22cm" svg:height="3cm"><draw:text-box>${p(title)}</draw:text-box></draw:frame>` +
  (lines.length ? `<draw:frame svg:x="2cm" svg:y="6cm" svg:width="22cm" svg:height="10cm"><draw:text-box>${lines.map(p).join("")}</draw:text-box></draw:frame>` : "") + `</draw:page>`;

// TIFF pages: stripes in a different colour per page, so a missing or repeated page shows.
function tiff(pages, file) {
  const folder = fs.mkdtempSync(path.join(os.tmpdir(), "pv-tiff-"));
  try {
    const inputs = pages.map((colour, i) => {
      const name = path.join(folder, `page${i + 1}.png`);
      fs.writeFileSync(name, png(600, 800, (x, y) => (Math.floor(y / 40) + i) % 2 ? colour : [255, 255, 255]));
      return name;
    });
    const out = path.join(folder, "out.tif");
    execFileSync("powershell.exe", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", path.join(here, "gdiplus.ps1"), inputs.join(";"), out, "tiffpages"]);
    write(file, fs.readFileSync(out));
  } finally { fs.rmSync(folder, { recursive: true, force: true }); }
}

export async function generateConverted() {
  // ---- OpenDocument text ----
  write("odt/simple.odt", await odf("odt", `<office:text>${p("Hello OpenDocument text.")}${p("Second paragraph.")}</office:text>`));
  rec("odt/simple.odt", "odt", "simple", { result: "open", kind: "word", text: ["Hello OpenDocument text"] });
  write("odt/complex.odt", await odf("odt",
    `<office:text><text:h text:outline-level="1">Hello complex OpenDocument</text:h>` +
    `<text:p text:style-name="B">Bold paragraph.</text:p><text:list><text:list-item>${p("First item")}</text:list-item><text:list-item>${p("Second item")}</text:list-item></text:list>` +
    `<table:table table:name="T"><table:table-column table:number-columns-repeated="2"/><table:table-row>${cell("Name")}${cell("Value")}</table:table-row><table:table-row>${cell("Code")}${cell("001")}</table:table-row></table:table>` +
    `${p("اردو: یہ ایک دستاویز ہے۔ سنڌي: سلام دنيا العربية: مرحبا بالعالم")}${p("中文 · 日本語 · 한국어")}` +
    `<text:p text:style-name="Break">Second page.</text:p></office:text>`,
    { styles: `<style:style style:name="B" style:family="paragraph"><style:text-properties fo:font-weight="bold"/></style:style><style:style style:name="Break" style:family="paragraph"><style:paragraph-properties fo:break-before="page"/></style:style>` }));
  rec("odt/complex.odt", "odt", "complex", { result: "open", kind: "word", pages: 2, text: ["Hello complex OpenDocument", "Second page"] }, own, { notes: "Heading, bold, list, table, right-to-left and CJK text, page break." });
  write("odt/attack-external.odt", await odf("odt",
    `<office:text>${p("Hello hostile OpenDocument: nothing outside this file may load.")}` +
    `<text:p><draw:frame svg:width="2cm" svg:height="2cm" text:anchor-type="as-char"><draw:image xlink:href="${LISTENER}/odt-remote-image.png" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad"/></draw:frame>` +
    `<draw:frame svg:width="2cm" svg:height="2cm" text:anchor-type="as-char"><draw:image xlink:href="${WEBDAV_UNC}\\odt-unc-image.png" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad"/></draw:frame></text:p>` +
    `<text:section text:name="Linked"><text:section-source xlink:href="${LISTENER}/odt-section.odt" xlink:type="simple"/></text:section>` +
    `<text:p><text:a xlink:type="simple" xlink:href="https://example.org/">A web link that stays (asks before opening)</text:a></text:p></office:text>`));
  rec("odt/attack-external.odt", "odt", "attack", { result: "open", kind: "word", removed: 3, text: ["Hello hostile OpenDocument"] }, own, { notes: "Remote and network-share pictures and a linked section are removed; the web hyperlink is kept." });
  write("odt/password.odt", await odf("odt", `<office:text>${p("Encrypted?")}</office:text>`, { manifestExtra: '<manifest:file-entry manifest:full-path="secret.xml" manifest:media-type="text/xml"><manifest:encryption-data manifest:checksum-type="SHA1" manifest:checksum="AAAA"/></manifest:file-entry>' }));
  rec("odt/password.odt", "odt", "password", { result: "error", error: "password" }, own, { notes: "Manifest declares encrypted content." });
  write("odt/zero-byte.odt", Buffer.alloc(0)); rec("odt/zero-byte.odt", "odt", "empty", { result: "error", error: "empty" }, "generator (empty file)");
  write("odt/not-a-document.odt", "Plain text saved with an .odt name.\r\n"); rec("odt/not-a-document.odt", "odt", "wrong-extension", { result: "error", error: "mismatch" }, "generator (text)");
  const odtComplex = fs.readFileSync(path.join(CORPUS, "odt", "complex.odt"));
  write("odt/damaged-truncated.odt", odtComplex.subarray(0, Math.floor(odtComplex.length / 2)));
  rec("odt/damaged-truncated.odt", "odt", "damaged", { result: "error", error: "damaged" }, `${own}, then truncated`);
  write("odt/docx-named.odt", fs.readFileSync(path.join(CORPUS, "docx", "simple.docx")));
  rec("odt/docx-named.odt", "odt", "wrong-extension", { result: "error", error: "rename" }, "docx fixture with an .odt name");

  // ---- OpenDocument spreadsheet ----
  const sheet = (name, rows) => `<table:table table:name="${name}">${rows.map(r => `<table:table-row>${r.join("")}</table:table-row>`).join("")}</table:table>`;
  write("ods/simple.ods", await odf("ods", `<office:spreadsheet>${sheet("Hello", [[cell("Hello OpenDocument spreadsheet"), cell(42)], [cell("Sum"), cell(84, "of:=[.B1]*2")]])}</office:spreadsheet>`));
  rec("ods/simple.ods", "ods", "simple", { result: "open", kind: "sheet", sheets: ["Hello"], cells: [{ sheet: "Hello", ref: "B1", text: "42" }, { sheet: "Hello", ref: "B2", text: "84" }] });
  write("ods/complex.ods", await odf("ods", `<office:spreadsheet>${sheet("Summary", [[cell("Hello items"), cell("Amount")], [cell("Alpha"), cell(10)], [cell("Beta"), cell(20)], [cell("Total"), cell(30, "of:=SUM([.B2:.B3])")], [cell("Stale"), cell(5, "of:=1+1")]])}` +
    `${sheet("Urdu", [[cell("اردو"), cell("سنڌي")]])}</office:spreadsheet>`));
  rec("ods/complex.ods", "ods", "complex", { result: "open", kind: "sheet", sheets: ["Summary", "Urdu"], cells: [{ sheet: "Summary", ref: "B4", text: "30" }, { sheet: "Summary", ref: "B5", text: "5" }, { sheet: "Urdu", ref: "A1", text: "اردو" }] }, own, { notes: "B5 is =1+1 saved as 5: the saved 5 must be shown (formulas are never recalculated)." });
  write("ods/attack-external.ods", await odf("ods", `<office:spreadsheet>` +
    `<table:table table:name="Hello"><table:table-source xlink:href="${LISTENER}/ods-table-source.ods" xlink:type="simple" table:table-name="Sheet1" table:mode="copy-all"/>` +
    `<table:table-row>${cell("Hello hostile spreadsheet")}${cell(7, `of:=['file:///${WEBDAV_UNC.replace(/\\/g, "/")}/linked.ods'#$Sheet1.A1]`)}</table:table-row></table:table></office:spreadsheet>`));
  rec("ods/attack-external.ods", "ods", "attack", { result: "open", kind: "sheet", sheets: ["Hello"], removed: 2, cells: [{ sheet: "Hello", ref: "B1", text: "7" }] }, own, { notes: "A linked table source and a formula referencing a file on a network share: both removed; the saved value 7 stays." });
  write("ods/zero-byte.ods", Buffer.alloc(0)); rec("ods/zero-byte.ods", "ods", "empty", { result: "error", error: "empty" }, "generator (empty file)");
  // Cell styles: a named style with a parent (styles.xml), automatic styles (content.xml) and a column default style.
  const SNS = NS.replace(' office:version="1.3"', "");
  write("ods/styles.ods", await odf("ods",
    `<office:spreadsheet><table:table table:name="Styles"><table:table-column/><table:table-column table:default-cell-style-name="ce1"/>` +
    `<table:table-row table:style-name="ro1"><table:table-cell table:style-name="ce2" office:value-type="string"><text:p>Hello header</text:p></table:table-cell><table:table-cell office:value-type="string"><text:p>Plain</text:p></table:table-cell></table:table-row>` +
    `<table:table-row table:style-name="ro2"><table:table-cell table:style-name="ce1" office:value-type="string"><text:p>Boxed</text:p></table:table-cell><table:table-cell office:value-type="string"><text:p>Column default</text:p></table:table-cell></table:table-row>` +
    `<table:table-row table:style-name="ro1"><table:table-cell office:value-type="string"><text:p>Third</text:p></table:table-cell></table:table-row>` +
    `<table:table-row table:style-name="ro1" table:number-rows-repeated="1000"><table:table-cell table:number-columns-repeated="2"/></table:table-row>` +
    `</table:table></office:spreadsheet>`,
    { styles: `<style:style style:name="ro1" style:family="table-row"><style:table-row-properties style:row-height="0.178in" style:use-optimal-row-height="true"/></style:style>` +
        `<style:style style:name="ro2" style:family="table-row"><style:table-row-properties style:row-height="0.625in" style:use-optimal-row-height="false"/></style:style>` +
        `<style:style style:name="ce1" style:family="table-cell" style:parent-style-name="Default"><style:table-cell-properties fo:border="0.74pt solid #ff0000"/><style:text-properties fo:font-style="italic"/></style:style>` +
        `<style:style style:name="ce2" style:family="table-cell" style:parent-style-name="Heading"><style:paragraph-properties fo:text-align="center"/></style:style>`,
      extra: { "styles.xml": `<?xml version="1.0" encoding="UTF-8"?><office:document-styles ${SNS} office:version="1.3"><office:styles>` +
        `<style:style style:name="Default" style:family="table-cell"><style:text-properties fo:font-size="10pt" fo:color="#000000"/></style:style>` +
        `<style:style style:name="Heading" style:family="table-cell" style:parent-style-name="Default"><style:table-cell-properties fo:background-color="#1d4ed8"/><style:text-properties fo:font-weight="bold" fo:color="#ffffff"/></style:style>` +
        `</office:styles></office:document-styles>` } }));
  rec("ods/styles.ods", "ods", "complex", { result: "open", kind: "sheet", sheets: ["Styles"],
    styles: [{ ref: "A1", bold: true, fill: "#1d4ed8", color: "#ffffff" }, { ref: "A2", italic: true, top: "1 solid #ff0000", left: "1 solid #ff0000" }, { ref: "B2", italic: true }, { ref: "B1", italic: true }],
    align: [{ ref: "A1", align: "c" }], defaultRowHeight: 12.82, rowHeights: [{ row: 2, points: 45 }] }, own, { notes: "Named style with a parent, automatic styles and a column default style. Row styles as LibreOffice writes them: the usual 0.178in rows (the default) and a 0.625in (45 pt) row 2." });
  // 12,000 rows: past the 10,000 kept in memory, so later rows come from the disk-backed row store.
  const bigRows = Array.from({ length: 12000 }, (_, i) => `<table:table-row>${cell(i === 0 ? "Hello big sheet" : `Row ${i + 1}`)}${cell(i + 1)}</table:table-row>`).join("");
  write("ods/large-12000-rows.ods", await odf("ods", `<office:spreadsheet><table:table table:name="Big">${bigRows}</table:table></office:spreadsheet>`));
  rec("ods/large-12000-rows.ods", "ods", "large", { result: "open", kind: "sheet", sheets: ["Big"], cells: [{ sheet: "Big", ref: "A1", text: "Hello big sheet" }], storedRows: 12000, lastRow: "Row 12000" }, own, { notes: "12,000 rows: rows past 10,000 stream to the row store." });

  // ---- OpenDocument presentation ----
  write("odp/simple.odp", await odf("odp", `<office:presentation>${slide("One", "Hello OpenDocument presentation")}</office:presentation>`));
  rec("odp/simple.odp", "odp", "simple", { result: "open", kind: "slides", pages: 1, text: ["Hello OpenDocument presentation"] });
  write("odp/complex.odp", await odf("odp", `<office:presentation>${slide("One", "Hello complex presentation", ["Point one", "Point two"])}${slide("Two", "Second slide", ["اردو · 中文"])}${slide("Three", "Third slide")}</office:presentation>`));
  rec("odp/complex.odp", "odp", "complex", { result: "open", kind: "slides", pages: 3, text: ["Hello complex presentation"] });
  write("odp/attack-remote-image.odp", await odf("odp", `<office:presentation><draw:page draw:name="One"><draw:frame svg:x="2cm" svg:y="2cm" svg:width="22cm" svg:height="3cm"><draw:text-box>${p("Hello hostile presentation")}</draw:text-box></draw:frame>` +
    `<draw:frame svg:x="2cm" svg:y="6cm" svg:width="5cm" svg:height="5cm"><draw:image xlink:href="${LISTENER}/odp-remote-image.png" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad"/></draw:frame></draw:page></office:presentation>`));
  rec("odp/attack-remote-image.odp", "odp", "attack", { result: "open", kind: "slides", removed: 1, text: ["Hello hostile presentation"] });

  // ---- RTF ----
  write("rtf/simple.rtf", "{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}}\\f0\\fs24 Hello Rich Text.\\par Second paragraph.\\par}\r\n");
  rec("rtf/simple.rtf", "rtf", "simple", { result: "open", kind: "word", text: ["Hello Rich Text"] }, "generator (RTF text)");
  write("rtf/complex.rtf", "{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}{\\f1 Segoe UI;}}\\f0\\fs28{\\b Hello complex Rich Text}\\par\\fs22 " +
    "{\\i Italic}, {\\ul underlined} and {\\b bold} text.\\par" +
    "\\trowd\\cellx3000\\cellx6000 Name\\cell Value\\cell\\row\\trowd\\cellx3000\\cellx6000 Code\\cell 001\\cell\\row\\pard\\par" +
    "{\\f1\\u1575?\\u1585?\\u1583?\\u1608? \\u20013?\\u25991?}\\par\\page Second page.\\par}\r\n");
  rec("rtf/complex.rtf", "rtf", "complex", { result: "open", kind: "word", pages: 2, text: ["Hello complex Rich Text", "Second page"] }, "generator (RTF text)", { notes: "Bold, italic, underline, a table, Urdu/Arabic and CJK characters, page break." });
  write("rtf/attack.rtf", `{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Arial;}}{\\*\\template ${LISTENER}/rtf-template.dot}\\f0 Hello hostile Rich Text.\\par\r\n` +
    `{\\field{\\*\\fldinst{INCLUDEPICTURE "${LISTENER}/rtf-includepicture.png" \\\\d}}{\\fldrslt{}}}\\par\r\n` +
    `{\\field{\\*\\fldinst{INCLUDETEXT "${WEBDAV_UNC.replace(/\\/g, "\\\\")}\\\\rtf-includetext.txt"}}{\\fldrslt{}}}\\par\r\n` +
    `{\\object\\objautlink\\objw100\\objh100{\\*\\objclass Word.Document.8}{\\*\\objdata 01050000}{\\result Linked object result}}\\par\r\n` +
    `{\\shp{\\*\\shpinst{\\sp{\\sn pibName}{\\sv ${LISTENER}/rtf-shape.png}}{\\sp{\\sn pibFlags}{\\sv 10}}}}\\par\r\n` +
    `{\\field{\\*\\fldinst{HYPERLINK "https://example.org/"}}{\\fldrslt{A web link that stays}}}\\par}\r\n`);
  rec("rtf/attack.rtf", "rtf", "attack", { result: "open", kind: "word", removed: 5, text: ["Hello hostile Rich Text"] }, "generator (RTF text)", { notes: "Template, INCLUDEPICTURE, INCLUDETEXT on a network share, an automatically updated linked object and a linked shape picture are removed; the web hyperlink is kept." });
  write("rtf/rtf-named.doc", fs.readFileSync(path.join(CORPUS, "rtf", "simple.rtf")));
  rec("rtf/rtf-named.doc", "doc", "wrong-extension", { result: "open", kind: "word", text: ["Hello Rich Text"] }, "generator (RTF text)", { notes: "RTF saved with a .doc name (as Word sometimes does): identified by content and opened as RTF." });
  write("rtf/zero-byte.rtf", Buffer.alloc(0)); rec("rtf/zero-byte.rtf", "rtf", "empty", { result: "error", error: "empty" }, "generator (empty file)");

  // ---- TIFF ----
  tiff([[200, 40, 40]], "tiff/simple.tif");
  rec("tiff/simple.tif", "tif", "simple", { result: "open", kind: "pages", pages: 1 }, "Windows GDI+ (System.Drawing), from the generator's PNG");
  tiff([[200, 40, 40], [40, 160, 40], [40, 40, 200]], "tiff/scan-3-pages.tiff");
  rec("tiff/scan-3-pages.tiff", "tiff", "complex", { result: "open", kind: "pages", pages: 3 }, "Windows GDI+ (System.Drawing), from the generator's PNGs", { notes: "A multi-page scan: three pages, red, green and blue stripes." });
  write("tiff/zero-byte.tif", Buffer.alloc(0)); rec("tiff/zero-byte.tif", "tif", "empty", { result: "error", error: "empty" }, "generator (empty file)");

  // ---- Word, Excel and PowerPoint 97-2003 (made by scripts/make-legacy-office.ps1, kept in git) ----
  const lo = "LibreOffice 26.2.6 from this corpus's own fixture (same engine as the viewer: safety and behaviour, not fidelity)";
  for (const [file, format, category, expect, notes] of [
    ["doc/simple.doc", "doc", "simple", { result: "open", kind: "word", text: ["Hello from a Word document"] }],
    ["doc/complex-20-pages.doc", "doc", "complex", { result: "open", kind: "word", text: ["Hello complex document"] }],
    ["doc/attack-remote-image.doc", "doc", "attack", { result: "open", kind: "word", removedAtLeast: 1, text: ["Hello"] }, "Linked picture as an INCLUDEPICTURE field to the listener: LibreOffice fetched it from the unprepared file."],
    ["doc/attack-unc-image.doc", "doc", "attack", { result: "open", kind: "word", removedAtLeast: 1, text: ["Hello"] }, "Linked picture on a network share."],
    ["xls/simple.xls", "xls", "simple", { result: "open", kind: "sheet", sheets: ["Hello"], cells: [{ sheet: "Hello", ref: "B1", text: "42" }] }],
    ["xls/complex.xls", "xls", "complex", { result: "open", kind: "sheet", sheets: ["Summary", "Urdu"], cells: [{ sheet: "Summary", ref: "B7", text: "$20.00" }] }, "Includes an external workbook reference."],
    ["xls/styles.xls", "xls", "complex", { result: "open", kind: "sheet", sheets: ["Styles"],
      styles: [{ ref: "A1", bold: true, color: "#c00000" }, { ref: "B1", italic: true }, { ref: "C1", underline: true }, { ref: "D1", strike: true },
        { ref: "A2", fill: "#ffff00" }, { ref: "C2", fill: "#00b050" }, { ref: "A3", bottom: "3 double #0000ff", left: "2 solid #000000" }, { ref: "B4", size: 1.455 }, { ref: "D4", wrap: true, vAlign: "top" },
        { ref: "G2", fill: "#ddebf7" }, { ref: "B8", fill: "#fce4d6" }, { ref: "G8", fill: "#fce4d6" }, { ref: "B7", fill: null }],
      align: [{ ref: "B3", align: "c" }, { ref: "C3", align: "r" }], hiddenColumns: ["E"], rowHeights: [{ row: 4, points: 45 }] }, "The styles workbook as .xls: fonts, fills, borders, alignment, row heights, a formatted whole column (COLINFO) and row (ROW with its own XF)."],
    ["xls/large-12000-rows.xls", "xls", "large", { result: "open", kind: "sheet", sheets: ["Big"], cells: [{ sheet: "Big", ref: "A1", text: "Hello big sheet" }], storedRows: 12000, lastRow: "Row 12000" }, "12,000 rows: rows past 10,000 stream to the row store."],
    ["xls/drawings.xls", "xls", "complex", { result: "open", kind: "sheet", sheets: ["Sales", "Trend"], cells: [{ sheet: "Sales", ref: "A7", text: "Hello pictures" }],
      drawings: [{ sheet: "Sales", pictures: 1, charts: ["column:Sales by month:2", "pie:January share:1"], values: ["120,150,90,170", "80,95,130,110"], categories: "Jan,Feb,Mar,Apr", titles: "Month|Units sold", labels: "120|150|90|170", values2: ["120,80"], categories2: "North,South", labels2: "North, 60%|South, 40%" }, { sheet: "Trend", pictures: 0, charts: ["line:Trend:2"] }] },
      "The pictures-and-charts workbook as .xls: the picture in the drawing group, charts as chart substreams whose series refer to the Sales cells (LibreOffice saves no chart cache), and the chart sheet as a worksheet with its chart."],
    ["xls/shapes.xls", "xls", "complex", { result: "open", kind: "sheet", sheets: ["Notes"], cells: [{ sheet: "Notes", ref: "A1", text: "Hello shapes" }],
      drawings: [{ sheet: "Notes", pictures: 0, shapes: ["rect:#ffffff:#bcbcbc:Hello shapes/A read-only note", "rect:#4f81bd:#3a5f8b:Approved", "rect:-:#c00000:", "line:-:#000000:",
        "rect:#70ad47:-:Next", "rect:#ffc000:-:", "rect:#5b9bd5:-:Step 1", "rect:#ffc000:-:Step 2"], parts: ["0,0,0.5,1", "0.5,0,0.5,0.499"] }] },
      "The shapes workbook as .xls by LibreOffice: Office Art shapes with OBJ and TXO records, and a group with child anchors. LibreOffice saves the rounded rectangle, ellipse, arrow and star as freeform outlines whose points refer to its geometry formulas; these are drawn as rectangles with their colours and text (a core test changes the ellipse to Excel's ellipse type)."],
    ["ods/shapes.ods", "ods", "complex", { result: "open", kind: "sheet", sheets: ["Notes"], cells: [{ sheet: "Notes", ref: "A1", text: "Hello shapes" }],
      drawings: [{ sheet: "Notes", pictures: 0, shapes: ["line:-:#000000:", "rect:#ffffff:#bcbcbc:Hello shapes/A read-only note", "roundRect:#4f81bd:#3a5f8b:Approved",
        "rect:#5b9bd5:-:Step 1", "ellipse:#ffc000:-:Step 2", "ellipse:-:#c00000:", "rightArrow:#70ad47:-:Next", "rect:#ffc000:-:"] }] },
      "The shapes workbook as .ods by LibreOffice: custom shapes (ooxml-* outlines) with graphic, paragraph and text styles, a connector with an end marker, and a group (draw:g) whose shapes keep their own positions. LibreOffice computes the rounded rectangle's outline as #3a5f8b and the text box's as #bcbcbc."],
    ["ods/drawings.ods", "ods", "complex", { result: "open", kind: "sheet", sheets: ["Sales", "Trend"], cells: [{ sheet: "Sales", ref: "A7", text: "Hello pictures" }],
      drawings: [{ sheet: "Sales", pictures: 1, charts: ["column:Sales by month:2", "pie:January share:1"], values: ["120,150,90,170", "80,95,130,110"], categories: "Jan,Feb,Mar,Apr", titles: "Month|Units sold", labels: "120|150|90|170", values2: ["120,80"], categories2: "North,South", labels2: "North, 60%|South, 40%" }, { sheet: "Trend", pictures: 0, charts: ["line:Trend:2"] }] },
      "The pictures-and-charts workbook as .ods: the picture and charts anchored to cells, the former chart sheet's chart anchored to the sheet; charts keep their cached data table."],
    ["ods/styles-libreoffice.ods", "ods", "complex", { result: "open", kind: "sheet", sheets: ["Styles"], cells: [{ sheet: "Styles", ref: "A8", text: "Filled row" }],
      styles: [{ ref: "A2", fill: "#ffff00" }, { ref: "G2", fill: "#ddebf7" }, { ref: "G6", fill: "#ddebf7" }, { ref: "B8", fill: "#fce4d6" }, { ref: "G8", fill: "#fce4d6" }, { ref: "B7", fill: null }], columnCount: 7 },
      "The styles workbook as .ods by LibreOffice: column G formatted through its default cell style (rows cover it with repeated empty cells), row 8 as one formatted empty cell repeated to the last column. Both are filled within the data (7 columns), not across the whole sheet."],
    ["xls/conditional.xls", "xls", "complex", { result: "open", kind: "sheet", sheets: ["Rules"], cells: [{ sheet: "Rules", ref: "A5", text: "40" }],
      styles: [{ ref: "A2", fill: null }, { ref: "A5", fill: "#ffc7ce", color: "#9c0006" }, { ref: "E2", italic: null }, { ref: "F7", fill: null }],
      workbookNotice: "2 conditional formatting rules are not shown" },
      "The conditional formatting workbook as .xls. LibreOffice keeps only the value rule and the formula rule as CF records (colour scale, data bar and icons are dropped) and writes the text rule with a type Excel 97-2003 does not define: the value rule is shown, the other two are counted in the notice."],
    ["ods/conditional.ods", "ods", "complex", { result: "open", kind: "sheet", sheets: ["Rules"], cells: [{ sheet: "Rules", ref: "A5", text: "40" }],
      styles: [{ ref: "A2", fill: null }, { ref: "A5", fill: "#ffc7ce", color: "#9c0006" }, { ref: "B2", fill: "#f8696b" }, { ref: "B3", fill: "#da7a6e" }, { ref: "B7", fill: "#63be7b" },
        { ref: "C2", bar: "10 #638ec6" }, { ref: "C7", bar: "90 #638ec6" }, { ref: "D2", icon: "arrow-down red" }, { ref: "D4", icon: "arrow-right yellow" }, { ref: "D7", icon: "arrow-up green" },
        { ref: "E2", italic: true }, { ref: "E3", italic: null }, { ref: "F7", fill: null }],
      workbookNotice: "1 conditional formatting rule is not shown" },
      "The conditional formatting workbook as .ods (calcext:conditional-formats with styles named by display name): every rule except the formula rule is shown; LibreOffice keeps its own data bar lengths (10 to 90)."],
    ["ppt/simple.ppt", "ppt", "simple", { result: "open", kind: "slides", text: ["Hello"] }],
    ["ppt/complex.ppt", "ppt", "complex", { result: "open", kind: "slides", text: ["Hello"] }],
    ["ppt/attack-remote-image.ppt", "ppt", "attack", { result: "open", kind: "slides", removedAtLeast: 1, text: ["Hello"] }, "Linked picture to the listener."],
    // Saved with the test password "viewer-test" by LibreOffice (scripts/make-protected-office.ps1): without a password
    // each asks for it; the core and smoke tests open them with it.
    ["doc/password.doc", "doc", "password", { result: "error", error: "password" }, "RC4 encryption (Office 97/2000 compatible), as LibreOffice saves it."],
    ["xls/password.xls", "xls", "password", { result: "error", error: "password" }, "RC4 encryption (Office 97/2000 compatible), as LibreOffice saves it."],
    ["odt/password-libreoffice.odt", "odt", "password", { result: "error", error: "password" }, "LibreOffice's ODF encryption: Argon2id key, AES-256-GCM."],
    ["ods/password.ods", "ods", "password", { result: "error", error: "password" }, "LibreOffice's ODF encryption: Argon2id key, AES-256-GCM."],
    ["odp/password.odp", "odp", "password", { result: "error", error: "password" }, "LibreOffice's ODF encryption: Argon2id key, AES-256-GCM."],
    ["odt/password-odf12.odt", "odt", "password", { result: "error", error: "password" }, "ODF 1.2 encryption (each part on its own): PBKDF2 key, AES-256-CBC, SHA-256 checksum."],
    ["ods/password-odf12.ods", "ods", "password", { result: "error", error: "password" }, "ODF 1.2 encryption (each part on its own): PBKDF2 key, AES-256-CBC, SHA-256 checksum."],
    // Windows metafile pictures (after 0.9.0), as LibreOffice stores them in .xls and .ods.
    ["xls/metafiles.xls", "xls", "complex", { result: "open", kind: "sheet", sheets: ["Sales", "Trend"], cells: [{ sheet: "Sales", ref: "A7", text: "Hello pictures" }], drawings: [{ sheet: "Sales", pictures: 2 }] },
      "The metafiles workbook as .xls: the pictures as EMF in the drawing group's picture store (zlib-compressed)."],
    ["ods/metafiles.ods", "ods", "complex", { result: "open", kind: "sheet", sheets: ["Sales", "Trend"], cells: [{ sheet: "Sales", ref: "A7", text: "Hello pictures" }], drawings: [{ sheet: "Sales", pictures: 2 }] },
      "The metafiles workbook as .ods: an EMF and a WMF, each with LibreOffice's PNG copy after it."],
    // Templates and the flat OpenDocument spreadsheet (0.8.0): shown as the document or workbook they hold.
    ["doc/template.dot", "dot", "simple", { result: "open", kind: "word", text: ["Hello from a Word document"] }, "Word 97-2003 template."],
    ["odt/template.ott", "ott", "simple", { result: "open", kind: "word", text: ["Hello from a Word document"] }, "OpenDocument text template: the private copy is labelled as a document."],
    ["xls/template.xlt", "xlt", "complex", { result: "open", kind: "sheet", sheets: ["Summary", "Urdu"], cells: [{ sheet: "Summary", ref: "B7", text: "$20.00" }] }, "Excel 97-2003 template of the complex workbook."],
    ["ods/template.ots", "ots", "complex", { result: "open", kind: "sheet", sheets: ["Summary", "Urdu"] }, "OpenDocument spreadsheet template of the complex workbook."],
    ["ods/complex.fods", "fods", "complex", { result: "open", kind: "sheet", sheets: ["Summary", "Urdu"] }, "The complex workbook as one flat XML file: hidden sheets stay hidden."],
    ["ods/styles.fods", "fods", "complex", { result: "open", kind: "sheet", sheets: ["Styles"], styles: [{ ref: "A2", fill: "#ffff00" }, { ref: "G2", fill: "#ddebf7" }, { ref: "B8", fill: "#fce4d6" }] },
      "The styles workbook as one flat XML file: styles come from the same file as the cells."],
  ]) if (fs.existsSync(path.join(CORPUS, file))) rec(file, format, category, expect, lo, notes ? { notes } : {});
  // Hostile: the .ods pictures workbook with three linked pictures in cell A7 (a web address, a network share and a
  // path outside the file). They must be counted and never opened.
  if (fs.existsSync(path.join(CORPUS, "ods", "drawings.ods"))) {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "ods", "drawings.ods")));
    const frame = (n, href) => `<draw:frame draw:name="Linked ${n}" svg:width="1in" svg:height="0.5in" svg:x="0in" svg:y="0in"><draw:image xlink:href="${href}" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad"/></draw:frame>`;
    const content = (await zip.file("content.xml").async("string")).replace("<text:p>Hello pictures</text:p>",
      "<text:p>Hello pictures</text:p>" + frame(1, `${LISTENER}/ods-linked-picture.png`) + frame(2, `file:${WEBDAV_UNC.replace(/\\/g, "/")}/ods-linked-picture.png`) + frame(3, "../ods-linked-picture.png"));
    if (!content.includes("Linked 3")) throw new Error("drawings.ods: cell A7 not found");
    zip.file("content.xml", content);
    zip.file("mimetype", "application/vnd.oasis.opendocument.spreadsheet", { compression: "STORE" });
    zip.forEach((_, f) => { f.date = FIXED_DATE; });
    write("ods/attack-linked-picture.ods", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    rec("ods/attack-linked-picture.ods", "ods", "attack", { result: "open", kind: "sheet", sheets: ["Sales", "Trend"], cells: [{ sheet: "Sales", ref: "A7", text: "Hello pictures" }], drawings: [{ sheet: "Sales", pictures: 1 }] },
      `${lo}, edited with JSZip`, { notes: "Three linked pictures (web address, network share, a path outside the file): never opened; the notice counts them; the cell text is unchanged." });
  }
  if (fs.existsSync(path.join(CORPUS, "xls", "simple.xls"))) {
    write("doc/xls-named.doc", fs.readFileSync(path.join(CORPUS, "xls", "simple.xls")));
    rec("doc/xls-named.doc", "doc", "wrong-extension", { result: "error", error: "mismatch" }, lo, { notes: "An Excel 97-2003 workbook with a .doc name." });
  }
  write("doc/zero-byte.doc", Buffer.alloc(0)); rec("doc/zero-byte.doc", "doc", "empty", { result: "error", error: "empty" }, "generator (empty file)");

  // ---- HEIC photos (made by scripts/make-heic.ps1 with Windows' HEIF encoder, kept in git) ----
  const heif = "Windows HEIF encoder (Microsoft HEIF Image Extensions and HEVC Video Extensions), from a picture drawn by the script (same codec the viewer decodes with)";
  for (const [file, category, expect, notes] of [
    ["heic/simple.heic", "simple", { result: "open", kind: "image", format: "HEIF", shown: [640, 480] }],
    ["heic/complex-rotated.heic", "complex", { result: "open", kind: "image", format: "HEIF", shown: [600, 800] }, "Stored landscape (800 × 600) with orientation 6, as phones save upright portrait photos: shown portrait, arrow pointing up."],
    ["heic/large-12mp.heic", "large", { result: "open", kind: "image", format: "HEIF", shown: [4032, 3024] }, "A 12-megapixel photo, the size of a typical phone photo."],
  ]) if (fs.existsSync(path.join(CORPUS, file))) rec(file, "heic", category, expect, heif, notes ? { notes } : {});
  if (fs.existsSync(path.join(CORPUS, "heic", "simple.heic"))) {
    const photo = fs.readFileSync(path.join(CORPUS, "heic", "simple.heic"));
    write("heic/damaged-truncated.heic", photo.subarray(0, Math.floor(photo.length / 2)));
    rec("heic/damaged-truncated.heic", "heic", "damaged", { result: "error", error: "damaged", stage: "worker" }, heif + ", then cut in half", { notes: "Passes the app's checks; Windows' decoder in the worker refuses it." });
  }
  write("heic/jpeg-named.heic", fs.readFileSync(path.join(CORPUS, "images", "simple.jpg")));
  rec("heic/jpeg-named.heic", "heic", "wrong-extension", { result: "open", kind: "image", format: "JPEG" }, "generator (the corpus's JPEG with a .heic name)", { notes: "Phones sometimes share JPEGs with a .heic name: identified by content and shown as JPEG, without the worker." });
  write("heic/zero-byte.heic", Buffer.alloc(0)); rec("heic/zero-byte.heic", "heic", "empty", { result: "error", error: "empty" }, "generator (empty file)");
}
