// Web pages (.html .htm .xhtml), saved web archives (.mht .mhtml) and EPUB books (0.8.0). Written here, independently
// of any browser or e-book tool. Hostile fixtures name the test listener and a network share in every way a page can
// refer to something: scripts, pictures, style sheets, imports, frames, objects, forms, refreshes, links and SVG.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import JSZip from "jszip";
import { CORPUS, GENERATED, LISTENER, WEBDAV_UNC, SAFE_RULES, FIXED_DATE, png, record, write } from "./lib.mjs";

const licence = "Generated by this repository; no third-party content";
const producer = "generator (web)";
const rec = (file, category, expect, notes) =>
  record({ id: `web-${file.replace(/[/.]/g, "-")}`, file: `web/${file}`, format: path.extname(file).slice(1), category, producer, licence, expect, rules: SAFE_RULES, ...(notes ? { notes } : {}) });

const unc = WEBDAV_UNC;
const dot = png(8, 8, () => [30, 120, 200]);
const dataPng = `data:image/png;base64,${dot.toString("base64")}`;

const simplePage = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Hello web page</title>
<style>body { font-family: Georgia, serif; } h1 { color: #1f4e79; } td, th { border: 1px solid #999; padding: 4px; }</style></head>
<body>
<h1>Hello web page</h1>
<p>A simple page with <strong>bold</strong>, <em>italic</em> and a <a href="https://example.com/">web link</a>.</p>
<table><tr><th>Name</th><th>Value</th></tr><tr><td>Code</td><td>001</td></tr><tr><td>Urdu</td><td dir="rtl">اردو سنڌي العربية</td></tr></table>
<p>Picture written into the page: <img src="${dataPng}" alt="Blue square" width="16" height="16"></p>
<p lang="zh">中文 日本語 한국어</p>
<p><a href="#end">Jump to the end</a></p>
<p id="end">The end.</p>
</body></html>
`;

const attackPage = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Hello hostile page</title>
<meta http-equiv="refresh" content="0; url=${LISTENER}/web-refresh">
<base href="${LISTENER}/web-base/">
<link rel="stylesheet" href="${LISTENER}/web-stylesheet.css">
<link rel="stylesheet" href="local.css">
<link rel="icon" href="${LISTENER}/web-icon.ico">
<link rel="preload" href="${LISTENER}/web-preload" as="fetch">
<style>@import url("${LISTENER}/web-import.css"); body { background: url("${LISTENER}/web-background.png"); } @font-face { font-family: X; src: url("${LISTENER}/web-font.woff"); }</style>
<script>fetch("${LISTENER}/web-script-fetch"); document.write('<img src="${LISTENER}/web-script-image">');</script>
<script src="${LISTENER}/web-script.js"></script>
</head>
<body onload="fetch('${LISTENER}/web-onload')" background="${LISTENER}/web-body-background.png">
<h1>Hello web page</h1>
<p>Every reference below points outside this file and must not be loaded.</p>
<img src="${LISTENER}/web-image.png" alt="Remote picture">
<img src="file:${unc.replace(/\\/g, "/")}/web-unc.png" alt="Network share picture">
<img src="${unc}\\web-unc-backslash.png" alt="Backslash share picture">
<img src="pictures/local.png" alt="Local picture">
<img src="${dataPng}" srcset="${LISTENER}/web-srcset.png 2x" alt="Srcset picture">
<img src="x" onerror="fetch('${LISTENER}/web-onerror')" alt="Handler picture">
<picture><source srcset="${LISTENER}/web-source.png"><img src="${LISTENER}/web-picture.png" alt="Picture element"></picture>
<div style="background-image: url('${LISTENER}/web-inline-style.png')">Styled box</div>
<iframe src="${LISTENER}/web-iframe"></iframe>
<object data="${LISTENER}/web-object"></object>
<embed src="${LISTENER}/web-embed">
<video src="${LISTENER}/web-video.mp4" poster="${LISTENER}/web-poster.png"></video>
<audio src="${LISTENER}/web-audio.mp3" autoplay></audio>
<form action="${LISTENER}/web-form"><input name="q" value="Hello form"><input type="image" src="${LISTENER}/web-input-image.png"><button formaction="${LISTENER}/web-formaction">Send</button></form>
<a href="javascript:fetch('${LISTENER}/web-javascript')">Script link</a>
<a href="${LISTENER}/web-link" ping="${LISTENER}/web-ping">Web link</a>
<a href="file:${unc.replace(/\\/g, "/")}/web-file-link">Share link</a>
<svg width="40" height="40"><image href="${LISTENER}/web-svg-image.png" width="40" height="40"/><use href="${LISTENER}/web-svg-use.svg#a"/><script>fetch("${LISTENER}/web-svg-script")</script></svg>
<math><mi xlink:href="${LISTENER}/web-math">x</mi></math>
<noscript><img src="${LISTENER}/web-noscript.png" alt="Noscript picture"></noscript>
<template><img src="${LISTENER}/web-template.png"></template>
</body></html>
`;

const xhtml = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"><head><title>Hello XHTML</title></head>
<body><h1>Hello web page</h1><p>Written as XHTML with a DOCTYPE that is never fetched.</p></body></html>
`;

// A page saved by Windows in Windows-1252, declared only by its <meta>.
const legacy = Buffer.from(`<html><head><meta http-equiv="Content-Type" content="text/html; charset=windows-1252"><title>Café</title></head><body><h1>Hello web page</h1><p>Café crème € 5</p></body></html>\r\n`, "latin1");
legacy[legacy.indexOf(Buffer.from("€", "latin1"))] = 0x80;   // the euro sign is 0x80 in Windows-1252

// ---- Saved web archives ----

// Quoted-printable with soft line breaks every 72 characters, never inside an escape.
function qp(text) {
  const escaped = Buffer.from(text, "utf8").toString("latin1").replace(/[=\u0080-ÿ]/g, c => "=" + c.charCodeAt(0).toString(16).toUpperCase().padStart(2, "0"));
  return escaped.split("\n").map(line => {
    const out = [];
    while (line.length > 73) {
      let cut = 72;
      while (line[cut - 1] === "=" || line[cut - 2] === "=") cut--;
      out.push(line.slice(0, cut) + "="); line = line.slice(cut);
    }
    out.push(line);
    return out.join("\r\n");
  }).join("\r\n");
}
function mht(parts, boundary = "----=_NextPart_PlainViewer") {
  const head = `From: <Saved by Plain Viewer's test generator>\r\nSubject: Hello web archive\r\nDate: Sat, 3 Oct 2026 00:00:00 +0000\r\nMIME-Version: 1.0\r\nContent-Type: multipart/related;\r\n\ttype="text/html";\r\n\tboundary="${boundary}"\r\n\r\nThis is a multi-part message in MIME format.\r\n\r\n`;
  return head + parts.map(p => `--${boundary}\r\n${p}\r\n`).join("") + `--${boundary}--\r\n`;
}
const archivePage = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Hello web archive</title><link rel="stylesheet" href="style.css"></head>
<body><h1>Hello web archive</h1><p>Saved with its picture and style sheet: <img src="images/dot.png" alt="Saved picture"> and by content ID: <img src="cid:dot@plainviewer" alt="Content ID picture"></p>
<p dir="rtl">اردو سنڌي</p></body></html>`;
const simpleMht = mht([
  `Content-Type: text/html;\r\n\tcharset="utf-8"\r\nContent-Transfer-Encoding: quoted-printable\r\nContent-Location: https://example.com/saved/page.html\r\n\r\n${qp(archivePage)}`,
  `Content-Type: text/css\r\nContent-Transfer-Encoding: quoted-printable\r\nContent-Location: https://example.com/saved/style.css\r\n\r\nh1 { color: #2e7d32; }`,
  `Content-Type: image/png\r\nContent-Transfer-Encoding: base64\r\nContent-Location: https://example.com/saved/images/dot.png\r\nContent-ID: <dot@plainviewer>\r\n\r\n${dot.toString("base64").match(/.{1,76}/g).join("\r\n")}`,
]);
const attackMht = mht([
  `Content-Type: text/html; charset="utf-8"\r\nContent-Transfer-Encoding: 8bit\r\nContent-Location: https://example.com/hostile.html\r\n\r\n` +
  `<html><body><h1>Hello web archive</h1><img src="${LISTENER}/mht-image.png"><img src="not-in-archive.png"><script>fetch("${LISTENER}/mht-script")</script><iframe src="${LISTENER}/mht-frame"></iframe></body></html>`,
]);

// ---- EPUB books ----

async function epub(file, { title, chapters, css = "", pictures = {}, fonts = {}, extra = {}, encryption }) {
  const zip = new JSZip();
  zip.file("mimetype", "application/epub+zip", { compression: "STORE" });
  zip.file("META-INF/container.xml", `<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>`);
  if (encryption) zip.file("META-INF/encryption.xml", encryption);
  const items = [], spine = [];
  chapters.forEach(([name, body, attributes = ""], i) => {
    zip.file(`OEBPS/text/${name}`, `<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"${attributes}><head><title>${title}</title><link rel="stylesheet" type="text/css" href="../styles/book.css"/></head><body>${body}</body></html>`);
    items.push(`<item id="c${i}" href="text/${name}" media-type="application/xhtml+xml"/>`); spine.push(`<itemref idref="c${i}"/>`);
  });
  zip.file("OEBPS/styles/book.css", css); items.push(`<item id="css" href="styles/book.css" media-type="text/css"/>`);
  Object.entries(pictures).forEach(([name, bytes], i) => { zip.file(`OEBPS/images/${name}`, bytes); items.push(`<item id="p${i}" href="images/${name}" media-type="image/png"/>`); });
  Object.entries(fonts).forEach(([name, bytes], i) => { zip.file(`OEBPS/fonts/${name}`, bytes); items.push(`<item id="f${i}" href="fonts/${name}" media-type="font/ttf"/>`); });
  for (const [name, text] of Object.entries(extra)) zip.file(`OEBPS/${name}`, text);
  zip.file("OEBPS/content.opf", `<?xml version="1.0" encoding="utf-8"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="id"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="id">urn:uuid:00000000-0000-4000-8000-000000000000</dc:identifier><dc:title>${title}</dc:title><dc:language>en</dc:language></metadata><manifest>${items.join("")}</manifest><spine>${spine.join("")}</spine></package>`);
  zip.forEach((_, f) => { f.date = FIXED_DATE; });
  write(`web/${file}`, await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE", mimeType: "application/epub+zip" }));
}

export async function generateWeb({ large }) {
  write("web/simple.html", simplePage);
  rec("simple.html", "simple", { result: "open", kind: "web", parts: 1, pictures: 0, text: ["Hello web page", "اردو"] });
  write("web/attack-active.html", attackPage);
  rec("attack-active.html", "attack", { result: "open", kind: "web", parts: 1, pictures: 0, text: ["Hello web page"] },
    "Scripts, handlers, refresh, base, remote and network-share pictures, style sheets, imports, fonts, frames, objects, media, forms, ping, javascript: links and SVG references: nothing may run or be requested.");
  write("web/simple.xhtml", xhtml);
  rec("simple.xhtml", "simple", { result: "open", kind: "web", parts: 1, text: ["Hello web page"] }, "XHTML with a DOCTYPE naming the W3C's DTD, which is never fetched.");
  write("web/windows-1252.htm", legacy);
  rec("windows-1252.htm", "complex", { result: "open", kind: "web", parts: 1, text: ["Café crème € 5"] }, "Encoding declared only by <meta>.");
  write("web/zero-byte.html", Buffer.alloc(0));
  rec("zero-byte.html", "empty", { result: "error", error: "empty" });
  write("web/png-named.html", dot);
  rec("png-named.html", "wrong-extension", { result: "error", error: "mismatch" }, "A PNG picture with an .html name.");

  write("web/simple.mht", simpleMht);
  rec("simple.mht", "simple", { result: "open", kind: "web", parts: 1, pictures: 1, styles: 1, text: ["Hello web archive", "اردو"] }, "Quoted-printable page, base64 picture found by its address and by content ID, style sheet.");
  write("web/attack-remote.mhtml", attackMht);
  rec("attack-remote.mhtml", "attack", { result: "open", kind: "web", parts: 1, pictures: 0, text: ["Hello web archive"] }, "Remote and missing pictures, a script and a frame: nothing may run or be requested.");

  const css = "body { font-family: serif; } h1 { color: #6a1b9a; } .note { font-style: italic; }";
  await epub("simple.epub", { title: "Hello book", css, pictures: { "dot.png": dot }, chapters: [
    ["chapter1.xhtml", `<h1>Hello book</h1><p>The first chapter, with a picture: <img src="../images/dot.png" alt="Blue square"/></p><p><a href="chapter2.xhtml#second">On to the second chapter</a></p>`],
    ["chapter2.xhtml", `<h1 id="second">Second chapter</h1><p class="note">The end of a short book.</p>`],
  ] });
  rec("simple.epub", "simple", { result: "open", kind: "web", parts: 2, pictures: 1, styles: 1, text: ["Hello book", "Second chapter"] });
  await epub("complex.epub", { title: "Hello complex book", css, pictures: { "cover.png": png(60, 90, (x, y) => [200, 60 + y, 80]) }, chapters: [
    ["cover.xhtml", `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 60 90"><image width="60" height="90" xlink:href="../images/cover.png"/></svg>`],
    ["urdu.xhtml", `<h1>اردو باب</h1><p>یہ ایک کتاب ہے۔ سنڌي: هي ڪتاب آهي.</p>`, ` xml:lang="ur" dir="rtl"`],
    ["cjk.xhtml", `<h1>中文章节</h1><p>你好世界。日本語。한국어.</p>`],
    ...Array.from({ length: 12 }, (_, i) => [`part${i + 1}.xhtml`, `<h1>Hello complex book, part ${i + 1}</h1>${Array.from({ length: 30 }, (_, p) => `<p>Paragraph ${p + 1} of part ${i + 1}.</p>`).join("")}<p><a href="#">Top</a> <a href="https://example.com/book">Publisher</a></p>`]),
  ] });
  rec("complex.epub", "complex", { result: "open", kind: "web", parts: 15, pictures: 1, text: ["اردو باب", "中文章节", "part 12"] }, "SVG cover referring to a picture in the book, right-to-left and CJK chapters, 15 chapters in reading order.");
  // A right-to-left book whose style sheet (not its markup) sets the direction, and a vertical-writing rule: its pages
  // must still run left to right (once collapsed to a single page) and each chapter keep its direction.
  await epub("rtl.epub", { title: "Hello right-to-left book", css: "html, body { direction: rtl; } .tategaki { writing-mode: vertical-rl; }",
    chapters: Array.from({ length: 6 }, (_, i) => [`chapter${i + 1}.xhtml`, `<h1>Hello باب ${i + 1}</h1>${Array.from({ length: 25 }, (_, p) => `<p>هذا نص عربي في الفقرة ${p + 1}. یہ اردو متن ہے۔</p>`).join("")}`]) });
  rec("rtl.epub", "complex", { result: "open", kind: "web", parts: 6, text: ["باب 6", "یہ اردو متن ہے"] }, "Direction set only by the book's style sheet (html and body right-to-left): pages still run left to right, one page per two chapters at least.");
  await epub("attack.epub", { title: "Hostile book", css: `@import url("${LISTENER}/epub-import.css"); body { background: url("${LISTENER}/epub-background.png"); }`, chapters: [
    ["hostile.xhtml", `<h1>Hello book</h1><script>fetch("${LISTENER}/epub-script")</script><img src="${LISTENER}/epub-image.png" alt="Remote"/><img src="../../../outside.png" alt="Outside the book"/><iframe src="${LISTENER}/epub-frame"></iframe><a href="javascript:fetch('${LISTENER}/epub-js')">Script link</a>`],
  ] });
  rec("attack.epub", "attack", { result: "open", kind: "web", parts: 1, pictures: 0, text: ["Hello book"] }, "Script, remote picture, a path climbing out of the book, frame, javascript: link and a style sheet importing from the listener.");
  await epub("drm.epub", { title: "Protected book", chapters: [["chapter1.xhtml", "<p>Encrypted</p>"]],
    encryption: `<?xml version="1.0"?><encryption xmlns="urn:oasis:names:tc:opendocument:xmlns:container" xmlns:enc="http://www.w3.org/2001/04/xmlenc#"><enc:EncryptedData><enc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/><enc:CipherData><enc:CipherReference URI="OEBPS/text/chapter1.xhtml"/></enc:CipherData></enc:EncryptedData></encryption>` });
  // Embedded fonts (after 0.9.0): Liberation Sans from the app's PDF.js fonts (SIL Open Font License), once as it is and
  // once obfuscated with the IDPF scheme (the first 1,040 bytes XORed with the SHA-1 of the book's identifier).
  {
    const font = fs.readFileSync(path.join(CORPUS, "..", "..", "src", "PlainViewer.App", "Assets", "pdf", "pdfjs", "standard_fonts", "LiberationSans-Regular.ttf"));
    const key = crypto.createHash("sha1").update("urn:uuid:00000000-0000-4000-8000-000000000000").digest();
    const obfuscated = Buffer.from(font);
    for (let i = 0; i < Math.min(1040, obfuscated.length); i++) obfuscated[i] ^= key[i % key.length];
    await epub("fonts.epub", { title: "Hello fonts", fonts: { "plain.ttf": font, "obfuscated.ttf": obfuscated },
      css: `@font-face { font-family: "Book Sans"; src: url("../fonts/plain.ttf"); } @font-face { font-family: "Book Hidden"; src: url(../fonts/obfuscated.ttf); } h1 { font-family: "Book Sans"; } p { font-family: "Book Hidden"; }`,
      encryption: `<?xml version="1.0"?><encryption xmlns="urn:oasis:names:tc:opendocument:xmlns:container" xmlns:enc="http://www.w3.org/2001/04/xmlenc#"><enc:EncryptedData><enc:EncryptionMethod Algorithm="http://www.idpf.org/2008/embedding"/><enc:CipherData><enc:CipherReference URI="OEBPS/fonts/obfuscated.ttf"/></enc:CipherData></enc:EncryptedData></encryption>`,
      chapters: [["chapter1.xhtml", "<h1>Hello fonts</h1><p>Set in the book's own fonts.</p>"]] });
    rec("fonts.epub", "complex", { result: "open", kind: "web", parts: 1, fonts: 2, text: ["Hello fonts"] }, "Two embedded fonts, one obfuscated (IDPF): both are restored, identified by their bytes and used by the book's style sheet.");
  }
  rec("drm.epub", "password", { result: "error", error: "password" }, "Chapter listed as encrypted (as DRM-protected books are): refused with a clear message.");
  write("web/zip-named.epub", fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
  rec("zip-named.epub", "wrong-extension", { result: "error", error: "mismatch" }, "An Excel workbook with an .epub name.");

  if (large) {
    // About 20 MB of HTML.
    fs.mkdirSync(GENERATED, { recursive: true });
    const rows = Array.from({ length: 120000 }, (_, i) => `<tr><td>${i}</td><td>Hello web row ${i}</td><td>${String(i).padStart(7, "0")}</td></tr>`).join("\n");
    fs.writeFileSync(path.join(GENERATED, "web-large.html"), `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Large page</title></head><body><h1>Hello large page</h1><table>${rows}</table></body></html>`);
    record({ id: "web-large-html", file: "generated/web-large.html", format: "html", category: "large", generated: true, producer, licence, expect: { result: "error", error: "too-large" }, rules: SAFE_RULES, notes: "Over the 16 MB web page limit: refused with a clear message." });
  }
}
