// An Excel binary workbook (.xlsb, after 0.9.0) written record by record from [MS-XLSB], because no independent
// producer is available here (LibreOffice opens .xlsb but cannot save it). It therefore proves the reader against the
// specification as this generator reads it, not against files saved by Excel.
import JSZip from "jszip";
import { SAFE_RULES, FIXED_DATE, record, write } from "./lib.mjs";

const licence = "Generated by this repository; no third-party content";
const producer = "generator (xlsb records written from [MS-XLSB] with JSZip)";

const varint = (value, maxBytes) => {
  const bytes = [];
  do { let b = value & 0x7f; value >>>= 7; if (value && bytes.length < maxBytes - 1) b |= 0x80; bytes.push(b); } while (value && bytes.length < maxBytes);
  return Buffer.from(bytes);
};
const rec = (type, ...parts) => { const body = Buffer.concat(parts); return Buffer.concat([varint(type, 2), varint(body.length, 4), body]); };
const u32 = v => { const b = Buffer.alloc(4); b.writeUInt32LE(v >>> 0); return b; };
const i32 = v => { const b = Buffer.alloc(4); b.writeInt32LE(v); return b; };
const u16 = v => { const b = Buffer.alloc(2); b.writeUInt16LE(v); return b; };
const f64 = v => { const b = Buffer.alloc(8); b.writeDoubleLE(v); return b; };
const wide = text => Buffer.concat([u32(text.length), Buffer.from(text, "utf16le")]);
const cell = (column, xf) => Buffer.concat([u32(column), u32(xf & 0xffffff)]);
const rk = integer => u32(((integer << 2) | 2) >>> 0);

export async function generateXlsb() {
  const strings = ["Hello binary", "Region", "Sindh"];
  const workbook = Buffer.concat([
    rec(0x0083), rec(0x0099, u32(0), u32(0), u32(0xffffffff)),                                // BrtBeginBook, BrtWbProp (1900 dates)
    rec(0x008f),                                                                                // BrtBeginBundleShs
    rec(0x009c, u32(0), u32(1), wide("rId1"), wide("Data")),                                   // visible
    rec(0x009c, u32(1), u32(2), wide("rId2"), wide("Secret")),                                 // hidden
    rec(0x0090), rec(0x0084)]);
  const sst = Buffer.concat([rec(0x009f, u32(strings.length), u32(strings.length)), ...strings.map(s => rec(0x0013, Buffer.from([0]), wide(s))), rec(0x00a0)]);
  // Number formats and three cell formats: general; a custom percentage, centred; a date.
  const xf = (format, align) => Buffer.concat([u16(0), u16(format), u16(0), u16(0), u16(0), Buffer.from([0, 0]), u16(align), u16(0)]);
  const styles = Buffer.concat([rec(0x0296), rec(0x0267, u32(1)), rec(0x002c, u16(164), wide("0.00%")), rec(0x0268),
    rec(0x0269, u32(3)), rec(0x002f, xf(0, 0)), rec(0x002f, xf(164, 2)), rec(0x002f, xf(14, 0)), rec(0x026a), rec(0x0297)]);
  const row = r => rec(0x0000, i32(r), u32(0), u16(300), Buffer.from([0, 0]), u32(0));
  const sheet1 = Buffer.concat([
    rec(0x0081),                                                                                  // BrtBeginSheet
    rec(0x0085), rec(0x0089, Buffer.alloc(30)),                                                  // views, with a frozen first row
    rec(0x0097, f64(0), f64(1), u32(1), u32(0), u32(2), Buffer.from([1])), rec(0x008a), rec(0x0086),
    rec(0x0186), rec(0x003c, i32(0), i32(0), i32(20 * 256), u32(0), u16(0)), rec(0x003c, i32(5), i32(5), i32(10 * 256), u32(0), u16(1)), rec(0x0187),
    rec(0x0091),                                                                                  // BrtBeginSheetData
    row(0), rec(0x0007, cell(0, 0), u32(0)), rec(0x0007, cell(1, 0), u32(1)), rec(0x0005, cell(2, 0), f64(3.25)), rec(0x0002, cell(3, 0), rk(42)),
    row(1), rec(0x0007, cell(0, 0), u32(2)), rec(0x0005, cell(1, 1), f64(0.256)), rec(0x0009, cell(2, 0), f64(99), u16(0), u32(0), u32(0)),
    rec(0x0004, cell(3, 0), Buffer.from([1])), rec(0x0003, cell(4, 0), Buffer.from([0x07])), rec(0x0006, cell(5, 0), wide("hidden column")),
    row(3), rec(0x0006, cell(0, 0), wide("اردو سنڌي العربية")), rec(0x0008, cell(1, 0), wide("cached text"), u16(0), u32(0), u32(0)),
    rec(0x0092),                                                                                  // BrtEndSheetData
    rec(0x00b1, u32(1)), rec(0x00b0, i32(3), i32(3), i32(1), i32(2)), rec(0x00b2),             // B4:C4 merged
    rec(0x0082)]);
  const sheet2 = Buffer.concat([rec(0x0081), rec(0x0091), row(0), rec(0x0006, cell(0, 0), wide("Hidden sheet text")), rec(0x0092), rec(0x0082)]);

  const zip = new JSZip();
  zip.file("[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
    `<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>` +
    `<Override PartName="/xl/workbook.bin" ContentType="application/vnd.ms-excel.sheet.binary.macroEnabled.main"/>` +
    `<Override PartName="/xl/worksheets/sheet1.bin" ContentType="application/vnd.ms-excel.worksheet"/><Override PartName="/xl/worksheets/sheet2.bin" ContentType="application/vnd.ms-excel.worksheet"/>` +
    `<Override PartName="/xl/sharedStrings.bin" ContentType="application/vnd.ms-excel.sharedStrings"/><Override PartName="/xl/styles.bin" ContentType="application/vnd.ms-excel.styles"/></Types>`);
  zip.file("_rels/.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.bin"/></Relationships>`);
  const R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";
  zip.file("xl/_rels/workbook.bin.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
    `<Relationship Id="rId1" Type="${R}/worksheet" Target="worksheets/sheet1.bin"/><Relationship Id="rId2" Type="${R}/worksheet" Target="worksheets/sheet2.bin"/>` +
    `<Relationship Id="rId3" Type="${R}/sharedStrings" Target="sharedStrings.bin"/><Relationship Id="rId4" Type="${R}/styles" Target="styles.bin"/></Relationships>`);
  zip.file("xl/workbook.bin", workbook);
  zip.file("xl/sharedStrings.bin", sst);
  zip.file("xl/styles.bin", styles);
  zip.file("xl/worksheets/sheet1.bin", sheet1);
  zip.file("xl/worksheets/sheet2.bin", sheet2);
  zip.forEach((_, f) => { f.date = FIXED_DATE; });
  write("xlsb/simple.xlsb", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
  record({ id: "xlsb-simple", file: "xlsb/simple.xlsb", format: "xlsb", category: "simple", producer, licence,
    expect: { result: "open", sheets: ["Data"], text: ["Hello binary"],
      cells: [{ sheet: "Data", ref: "A1", text: "Hello binary" }, { sheet: "Data", ref: "C1", text: "3.25" }, { sheet: "Data", ref: "D1", text: "42" },
        { sheet: "Data", ref: "B2", text: "25.60%" }, { sheet: "Data", ref: "C2", text: "99" }, { sheet: "Data", ref: "D2", text: "TRUE" }, { sheet: "Data", ref: "E2", text: "#DIV/0!" },
        { sheet: "Data", ref: "A4", text: "اردو سنڌي العربية" }, { sheet: "Data", ref: "B4", text: "cached text" }],
      align: [{ ref: "B2", align: "c" }], hiddenColumns: ["F"], workbookNotice: "1 hidden sheet stays hidden" }, rules: SAFE_RULES,
    notes: "Shared strings, inline strings, numbers (double and RK), a cached formula number and text, TRUE, an error, a custom percentage format (centred), a hidden column, a merged range, a frozen first row and a hidden sheet." });
  write("xlsb/zero-byte.xlsb", Buffer.alloc(0));
  record({ id: "xlsb-zero-byte", file: "xlsb/zero-byte.xlsb", format: "xlsb", category: "empty", producer: "generator (empty file)", licence, expect: { result: "error", error: "empty" }, rules: SAFE_RULES });
}
