import ExcelJS from "exceljs";
import JSZip from "jszip";
import officeCrypto from "officecrypto-tool";
import CFB from "cfb";
import fs from "node:fs";
import path from "node:path";
import { write, record, packageVersion, chartPng, LISTENER, WEBDAV_UNC, SAFE_RULES, CORPUS } from "./lib.mjs";

const producer = `exceljs ${packageVersion("exceljs")} (Node)`;
const licence = "Generated by this repository; no third-party content";
const date = new Date(Date.UTC(2026, 8, 27));

function workbook() {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Plain Viewer corpus"; wb.created = date; wb.modified = date;
  return wb;
}

// ZIP output from exceljs embeds the current time in entry headers; rewrite entries with a fixed date so
// regenerated fixtures are identical.
async function stable(buffer) {
  const zip = await JSZip.loadAsync(buffer);
  zip.forEach((_, file) => { file.date = date; });
  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE", compressionOptions: { level: 6 } });
}

// Cell styles: fonts, fills (direct and theme colours with tint), borders, alignment, indent, wrap, text that spills
// over empty neighbours, a styled empty cell and a hidden column.
function stylesWorkbook() {
  const wb = workbook();
  const ws = wb.addWorksheet("Styles");
  ws.columns = [{ width: 14 }, { width: 14 }, { width: 14 }, { width: 14 }, { width: 14, hidden: true }, { width: 14 }];
  const set = (ref, value, style) => { const cell = ws.getCell(ref); cell.value = value; Object.assign(cell, style); };
  set("A1", "Bold red", { font: { bold: true, color: { argb: "FFC00000" } } });
  set("B1", "Italic", { font: { italic: true } });
  set("C1", "Underlined", { font: { underline: true } });
  set("D1", "Struck", { font: { strike: true } });
  set("A2", "Yellow fill", { fill: { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFFF00" } } });
  set("B2", "Theme fill", { fill: { type: "pattern", pattern: "solid", fgColor: { theme: 4, tint: 0.3999755851924192 } } });
  set("C2", null, { fill: { type: "pattern", pattern: "solid", fgColor: { argb: "FF00B050" } } });
  set("A3", "Boxed", { border: { top: { style: "thin", color: { argb: "FF0000FF" } }, bottom: { style: "double", color: { argb: "FF0000FF" } },
    left: { style: "medium" }, right: { style: "dashed", color: { argb: "FFFF0000" } } } });
  set("B3", "Centred", { alignment: { horizontal: "center" } });
  set("C3", "Right", { alignment: { horizontal: "right" } });
  set("D3", 1234.5, { alignment: { horizontal: "left" }, numFmt: "#,##0.00" });
  set("A4", "Indented", { alignment: { indent: 2 } });
  set("B4", "Big text", { font: { size: 16 } });
  set("C4", "Consolas", { font: { name: "Consolas" } });
  set("D4", "Wrapped text that is long", { alignment: { wrapText: true, vertical: "top" } });
  // Spill: A5 runs over the empty B5:D5; A6 cannot, because B6 has content.
  set("A5", "Hello spill: this text is longer than its column and runs over the empty cells beside it", {});
  set("A6", "No room to spill here", {}); set("B6", "Neighbour", {});
  set("F1", "After hidden E", {});
  // Pattern fills: a grey shade (drawn blended), crosshatching on a colour and thin lines on the default white.
  const patterned = (pattern, fg, bg) => ({ fill: { type: "pattern", pattern, fgColor: { argb: fg }, ...(bg ? { bgColor: { argb: bg } } : {}) } });
  set("C6", null, patterned("lightGray", "FF000000", "FFFFFFFF"));
  set("D6", null, patterned("darkTrellis", "FFC00000", "FFFFFF00"));
  set("F6", null, patterned("lightHorizontal", "FF0070C0"));
  ws.getRow(4).height = 45;                                  // tall enough for D4's wrapped text
  // Whole column G and whole row 8 filled: Excel saves no cells for their empty part (the row's fill wins in G8).
  ws.getColumn(7).width = 10;
  ws.getColumn(7).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFDDEBF7" } };
  ws.getRow(8).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFCE4D6" } };
  ws.getCell("A8").value = "Filled row";
  return wb;
}

// A chart part: one chart of the given kind with cached categories and values, and references to the cells they came
// from (series in columns B, C, ... of rows 2-5 by default; a pie chart of one row passes `across`; other workbooks
// pass `refs` with their own name(i), cat and val(i) references, and `stacked` for a stacked column chart). `labels`
// lists the data label parts to show ("value", "category", "percent"); `axisTitles` is { cat, val }.
export function chartXml({ kind, title, categories, series, across, refs, stacked, labels, axisTitles }) {
  const strCache = values => `<c:strCache><c:ptCount val="${values.length}"/>${values.map((v, i) => `<c:pt idx="${i}"><c:v>${v}</c:v></c:pt>`).join("")}</c:strCache>`;
  const numCache = values => `<c:numCache><c:formatCode>General</c:formatCode><c:ptCount val="${values.length}"/>${values.map((v, i) => `<c:pt idx="${i}"><c:v>${v}</c:v></c:pt>`).join("")}</c:numCache>`;
  const nameRef = i => refs ? refs.name(i) : `Sales!$${"BC"[i] ?? "B"}$1`;
  const catRef = refs ? refs.cat : across ? across.cat : "Sales!$A$2:$A$5";
  const valRef = i => refs ? refs.val(i) : across ? across.val : `Sales!$${"BC"[i] ?? "B"}$2:$${"BC"[i] ?? "B"}$5`;
  const ser = series.map(([name, values, colour], i) => `<c:ser><c:idx val="${i}"/><c:order val="${i}"/><c:tx><c:strRef><c:f>${nameRef(i)}</c:f>${strCache([name])}</c:strRef></c:tx>` +
    (colour ? `<c:spPr><a:solidFill><a:srgbClr val="${colour}"/></a:solidFill></c:spPr>` : "") +
    `<c:cat><c:strRef><c:f>${catRef}</c:f>${strCache(categories)}</c:strRef></c:cat>` +
    `<c:val><c:numRef><c:f>${valRef(i)}</c:f>${numCache(values)}</c:numRef></c:val></c:ser>`).join("");
  const round = kind === "pieChart" || kind === "doughnutChart";
  const axes = round ? "" : '<c:axId val="1"/><c:axId val="2"/>';
  // Data labels and axis titles, in the element order the chart schema requires.
  const show = (element, part) => `<c:${element} val="${labels?.includes(part) ? 1 : 0}"/>`;
  const dLbls = labels ? `<c:dLbls><c:showLegendKey val="0"/>${show("showVal", "value")}${show("showCatName", "category")}<c:showSerName val="0"/>${show("showPercent", "percent")}<c:showBubbleSize val="0"/></c:dLbls>` : "";
  const axisTitle = text => text ? `<c:title><c:tx><c:rich><a:bodyPr/><a:p><a:r><a:t>${text}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title>` : "";
  const body = kind === "barChart" ? `<c:barChart><c:barDir val="col"/><c:grouping val="${stacked ? "stacked" : "clustered"}"/><c:varyColors val="0"/>${ser}${dLbls}${stacked ? '<c:overlap val="100"/>' : ""}${axes}</c:barChart>`
    : kind === "lineChart" ? `<c:lineChart><c:grouping val="standard"/><c:varyColors val="0"/>${ser}${dLbls}<c:marker val="1"/>${axes}</c:lineChart>`
    : kind === "doughnutChart" ? `<c:doughnutChart><c:varyColors val="1"/>${ser}${dLbls}<c:firstSliceAng val="0"/><c:holeSize val="50"/></c:doughnutChart>`
    : `<c:pieChart><c:varyColors val="1"/>${ser}${dLbls}<c:firstSliceAng val="0"/></c:pieChart>`;
  const axisParts = round ? "" : `<c:catAx><c:axId val="1"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="b"/>${axisTitle(axisTitles?.cat)}<c:crossAx val="2"/></c:catAx>` +
    `<c:valAx><c:axId val="2"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="l"/><c:majorGridlines/>${axisTitle(axisTitles?.val)}<c:crossAx val="1"/></c:valAx>`;
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
    `<c:chart><c:title><c:tx><c:rich><a:bodyPr/><a:p><a:r><a:t>${title}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title><c:autoTitleDeleted val="0"/><c:plotArea><c:layout/>${body}${axisParts}</c:plotArea>` +
    `<c:legend><c:legendPos val="b"/><c:overlay val="0"/></c:legend><c:plotVisOnly val="1"/></c:chart></c:chartSpace>`;
}

export async function generateXlsx({ large }) {
  {
    write("xlsx/styles.xlsx", await stable(await stylesWorkbook().xlsx.writeBuffer()));
    record({ id: "xlsx-styles", file: "xlsx/styles.xlsx", format: "xlsx", category: "complex", producer, licence,
      expect: { result: "open", sheets: ["Styles"],
        cells: [{ sheet: "Styles", ref: "D3", text: "1,234.50" }, { sheet: "Styles", ref: "A5", text: "Hello spill: this text is longer than its column and runs over the empty cells beside it" }],
        styles: [
          { ref: "A1", bold: true, color: "#c00000" }, { ref: "B1", italic: true }, { ref: "C1", underline: true }, { ref: "D1", strike: true },
          { ref: "A2", fill: "#ffff00" }, { ref: "B2", fill: "#95b3d7" }, { ref: "C2", fill: "#00b050" },
          { ref: "A3", top: "1 solid #0000ff", bottom: "3 double #0000ff", left: "2 solid #000000", right: "1 dashed #ff0000" },
          { ref: "A4", indent: 2 }, { ref: "B4", size: 1.455 }, { ref: "C4", font: "Consolas" }, { ref: "D4", wrap: true, vAlign: "top" },
          { ref: "C6", fill: "#bfbfbf", pattern: null }, { ref: "D6", fill: "#ffff00", pattern: "darkTrellis #c00000" }, { ref: "F6", fill: "#ffffff", pattern: "lightHorizontal #0070c0" },
          { ref: "G2", fill: "#ddebf7" }, { ref: "G6", fill: "#ddebf7" }, { ref: "B8", fill: "#fce4d6" }, { ref: "G8", fill: "#fce4d6" }, { ref: "B7", fill: null }],
        align: [{ ref: "B3", align: "c" }, { ref: "C3", align: "r" }, { ref: "D3", align: "l" }],
        hiddenColumns: ["E"], defaultRowHeight: 15, rowHeights: [{ row: 4, points: 45 }] },
      rules: SAFE_RULES, notes: "Theme fill: accent1 of the Office 2007 theme exceljs writes (#4f81bd) lightened by 40% is #95b3d7, as Excel shows it. Wrapped text shows its first line (row heights are not applied). A5 must spill over B5:D5; A6 must not." });
  }
  // Conditional formatting, worked out from saved values; the expression rule F2>2 is evaluated for each cell (after 0.9.0).
  {
    const wb = workbook();
    const ws = wb.addWorksheet("Rules");
    ws.getRow(1).values = ["Hello: over 35", "Colour scale", "Data bar", "Icons", "Text", "Formula rule"];
    const words = ["apple pie", "banana", "pineapple", "cherry", "grape", "melon"];
    for (let i = 0; i < 6; i++) ws.getRow(i + 2).values = [10 * (i + 1), 10 * (i + 1), 10 * (i + 1), 10 * (i + 1), words[i], i];
    const fill = argb => ({ type: "pattern", pattern: "solid", bgColor: { argb } });
    ws.addConditionalFormatting({ ref: "A2:A7", rules: [{ type: "cellIs", operator: "greaterThan", formulae: [35], priority: 1,
      style: { fill: fill("FFFFC7CE"), font: { color: { argb: "FF9C0006" } } } }] });
    ws.addConditionalFormatting({ ref: "B2:B7", rules: [{ type: "colorScale", priority: 2, cfvo: [{ type: "min" }, { type: "max" }],
      color: [{ argb: "FFF8696B" }, { argb: "FF63BE7B" }] }] });
    ws.addConditionalFormatting({ ref: "C2:C7", rules: [{ type: "dataBar", priority: 3, minLength: 0, maxLength: 100,
      cfvo: [{ type: "min" }, { type: "max" }], color: { argb: "FF638EC6" } }] });
    ws.addConditionalFormatting({ ref: "D2:D7", rules: [{ type: "iconSet", iconSet: "3Arrows", priority: 4,
      cfvo: [{ type: "percent", value: 0 }, { type: "percent", value: 33 }, { type: "percent", value: 67 }] }] });
    ws.addConditionalFormatting({ ref: "E2:E7", rules: [{ type: "containsText", operator: "containsText", text: "apple", priority: 5,
      style: { font: { italic: true } } }] });
    ws.addConditionalFormatting({ ref: "F2:F7", rules: [{ type: "expression", formulae: ["F2>2"], priority: 6, style: { fill: fill("FFFFEB9C") } }] });
    // exceljs leaves out the text attribute that Excel writes on text rules; add it as Excel does. The data bar's id
    // (random in exceljs) is fixed so the file is the same every time.
    const zip = await JSZip.loadAsync(await wb.xlsx.writeBuffer());
    const sheetXml = await zip.file("xl/worksheets/sheet1.xml").async("string");
    zip.file("xl/worksheets/sheet1.xml", sheetXml.replace('type="containsText" dxfId="1"', 'type="containsText" dxfId="1" operator="containsText" text="apple"')
      .replace(/\{[0-9A-Fa-f-]{36}\}/g, "{00000000-0000-4000-8000-000000000001}"));
    write("xlsx/conditional.xlsx", await stable(await zip.generateAsync({ type: "nodebuffer" })));
    record({ id: "xlsx-conditional", file: "xlsx/conditional.xlsx", format: "xlsx", category: "complex", producer, licence,
      expect: { result: "open", sheets: ["Rules"], cells: [{ sheet: "Rules", ref: "A5", text: "40" }, { sheet: "Rules", ref: "E2", text: "apple pie" }],
        styles: [
          { ref: "A2", fill: null }, { ref: "A5", fill: "#ffc7ce", color: "#9c0006" },
          { ref: "B2", fill: "#f8696b" }, { ref: "B3", fill: "#da7a6e" }, { ref: "B7", fill: "#63be7b" },
          { ref: "C2", bar: "0 #638ec6" }, { ref: "C7", bar: "100 #638ec6" },
          { ref: "D2", icon: "arrow-down red" }, { ref: "D4", icon: "arrow-right yellow" }, { ref: "D7", icon: "arrow-up green" },
          { ref: "E2", italic: true }, { ref: "E3", italic: null }, { ref: "E4", italic: true },
          { ref: "F4", fill: null }, { ref: "F5", fill: "#ffeb9c" }, { ref: "F7", fill: "#ffeb9c" }] },
      rules: SAFE_RULES, notes: "Rules applied to saved values: cell value, colour scale, data bar, icon set, text contains, and the formula rule F2>2 (relative: F5 to F7 hold 3 to 5)." });
  }
  // More conditional formatting rule kinds: between, bottom N, top percent, below average, blanks and errors, a
  // three-colour scale, traffic lights, rating bars without the value, duplicates and unique values (written as Excel
  // writes them; exceljs cannot), begins/ends with, and "stop if true".
  {
    const wb = workbook();
    const ws = wb.addWorksheet("More");
    ws.getRow(1).values = ["Hello: between", "Bottom 2", "Top 50%", "Below average", "Blanks, errors", "3 colours", "Lights", "Ratings", "Duplicates", "Unique", "Text", "Stop"];
    const numbers = [5, 15, 25, 35, 45, 55], words = ["a", "b", "a", "c", "b", "d"], fruit = ["apple", "banana", "cherry", "date", "fig", "kiwi"];
    for (let i = 0; i < 6; i++) {
      const row = ws.getRow(i + 2);
      row.values = [numbers[i], numbers[i], numbers[i], numbers[i], null, numbers[i], numbers[i], numbers[i], words[i], words[i], fruit[i], numbers[i]];
    }
    ws.getCell("E2").value = "x"; ws.getCell("E4").value = { error: "#DIV/0!" }; ws.getCell("E5").value = "y"; ws.getCell("E6").value = "z"; ws.getCell("E7").value = "w";
    const fill = argb => ({ fill: { type: "pattern", pattern: "solid", bgColor: { argb } } });
    let priority = 0;
    const add = (ref, rule) => ws.addConditionalFormatting({ ref, rules: [{ priority: ++priority, ...rule }] });
    add("A2:A7", { type: "cellIs", operator: "between", formulae: [20, 40], style: fill("FFFFC7CE") });              // dxf 0
    add("B2:B7", { type: "top10", rank: 2, bottom: true, style: fill("FFC6EFCE") });                                 // dxf 1
    add("C2:C7", { type: "top10", rank: 50, percent: true, style: fill("FFC6EFCE") });                               // dxf 2
    add("D2:D7", { type: "aboveAverage", aboveAverage: false, style: fill("FFFFEB9C") });                            // dxf 3
    add("E2:E7", { type: "containsText", operator: "containsBlanks", style: fill("FFD9D9D9") });                      // dxf 4
    add("E2:E7", { type: "containsText", operator: "containsErrors", style: { font: { italic: true } } });           // dxf 5
    add("F2:F7", { type: "colorScale", cfvo: [{ type: "min" }, { type: "percentile", value: 50 }, { type: "max" }], color: [{ argb: "FFF8696B" }, { argb: "FFFFEB84" }, { argb: "FF63BE7B" }] });
    add("G2:G7", { type: "iconSet", iconSet: "3TrafficLights1", cfvo: [{ type: "percent", value: 0 }, { type: "percent", value: 33 }, { type: "percent", value: 67 }] });
    add("H2:H7", { type: "iconSet", iconSet: "5Rating", cfvo: [0, 20, 40, 60, 80].map(value => ({ type: "percent", value })) });
    add("L2:L7", { type: "cellIs", operator: "greaterThan", formulae: [10], stopIfTrue: true, style: fill("FFFF0000") });   // dxf 6
    add("L2:L7", { type: "cellIs", operator: "greaterThan", formulae: [0], style: { font: { bold: true } } });             // dxf 7
    const zip = await JSZip.loadAsync(await wb.xlsx.writeBuffer());
    let sheetXml = await zip.file("xl/worksheets/sheet1.xml").async("string");
    const raw = (ref, rule) => `<conditionalFormatting sqref="${ref}">${rule}</conditionalFormatting>`;
    const extra = raw("I2:I7", '<cfRule type="duplicateValues" dxfId="0" priority="20"/>') + raw("J2:J7", '<cfRule type="uniqueValues" dxfId="1" priority="21"/>') +
      raw("K2:K7", '<cfRule type="beginsWith" dxfId="7" priority="22" operator="beginsWith" text="b"><formula>LEFT(K2,1)="b"</formula></cfRule>') +
      raw("K2:K7", '<cfRule type="endsWith" dxfId="5" priority="23" operator="endsWith" text="y"><formula>RIGHT(K2,1)="y"</formula></cfRule>');
    const first = sheetXml.indexOf("<conditionalFormatting");
    if (first < 0) throw new Error("conditional-more.xlsx: no conditional formatting written");
    sheetXml = sheetXml.slice(0, first) + extra + sheetXml.slice(first);
    sheetXml = sheetXml.replace('<iconSet iconSet="5Rating">', '<iconSet iconSet="5Rating" showValue="0">');
    // exceljs leaves out stopIfTrue; Excel writes it on the rule.
    sheetXml = sheetXml.replace('<cfRule type="cellIs" dxfId="6" priority="10" operator="greaterThan">', '<cfRule type="cellIs" dxfId="6" priority="10" stopIfTrue="1" operator="greaterThan">');
    if (!sheetXml.includes('stopIfTrue="1"')) throw new Error("conditional-more.xlsx: stop rule not found");
    if (!sheetXml.includes('showValue="0"')) throw new Error("conditional-more.xlsx: 5Rating not found");
    zip.file("xl/worksheets/sheet1.xml", sheetXml.replace(/\{[0-9A-Fa-f-]{36}\}/g, "{00000000-0000-4000-8000-000000000002}"));
    write("xlsx/conditional-more.xlsx", await stable(await zip.generateAsync({ type: "nodebuffer" })));
    record({ id: "xlsx-conditional-more", file: "xlsx/conditional-more.xlsx", format: "xlsx", category: "complex", producer: `${producer}, four rules added as XML with JSZip`, licence,
      expect: { result: "open", sheets: ["More"], cells: [{ sheet: "More", ref: "A5", text: "35" }, { sheet: "More", ref: "H2", text: "" }],
        styles: [
          { ref: "A3", fill: null }, { ref: "A4", fill: "#ffc7ce" }, { ref: "A5", fill: "#ffc7ce" }, { ref: "A6", fill: null },
          { ref: "B2", fill: "#c6efce" }, { ref: "B3", fill: "#c6efce" }, { ref: "B4", fill: null },
          { ref: "C4", fill: null }, { ref: "C5", fill: "#c6efce" }, { ref: "C7", fill: "#c6efce" },
          { ref: "D2", fill: "#ffeb9c" }, { ref: "D4", fill: "#ffeb9c" }, { ref: "D5", fill: null },
          { ref: "E3", fill: "#d9d9d9" }, { ref: "E2", fill: null }, { ref: "E4", italic: true },
          { ref: "F2", fill: "#f8696b" }, { ref: "F7", fill: "#63be7b" },
          { ref: "G2", icon: "circle red" }, { ref: "G7", icon: "circle green" }, { ref: "H2", icon: "bar-0 blue" }, { ref: "H7", icon: "bar-4 blue" },
          { ref: "I2", fill: "#ffc7ce" }, { ref: "I5", fill: null }, { ref: "J5", fill: "#c6efce" }, { ref: "J2", fill: null },
          { ref: "K3", bold: true }, { ref: "K4", italic: true }, { ref: "K2", bold: null },
          { ref: "L2", fill: null, bold: true }, { ref: "L3", fill: "#ff0000", bold: null }] },
      rules: SAFE_RULES, notes: "Rule kinds not in conditional.xlsx. Between 20 and 40; bottom 2; top 50% of six values (three); below the average of 30; a blank and an error cell; a 3-colour scale with a 50th-percentile midpoint; 3 traffic lights and 5 rating bars with the value hidden; duplicates and unique values; begins with b, ends with y; L: > 10 fills red and stops, so only cells up to 10 are bold." });
  }
  // Simple
  {
    const wb = workbook();
    const ws = wb.addWorksheet("Hello");
    ws.getCell("A1").value = "Hello spreadsheet";
    ws.getCell("B1").value = 42;
    ws.getCell("A2").value = "Second row";
    ws.getCell("B2").value = 3.14;
    write("xlsx/simple.xlsx", await stable(await wb.xlsx.writeBuffer()));
    record({ id: "xlsx-simple", file: "xlsx/simple.xlsx", format: "xlsx", category: "simple", producer, licence,
      expect: { result: "open", sheets: ["Hello"], text: ["Hello spreadsheet"], cells: [{ sheet: "Hello", ref: "B1", text: "42" }, { sheet: "Hello", ref: "B2", text: "3.14" }] },
      rules: SAFE_RULES });
  }

  // Complex: formats, merge, frozen panes, widths, cached and missing formula results, RTL, hidden sheets.
  {
    const wb = workbook();
    const ws = wb.addWorksheet("Summary", { views: [{ state: "frozen", xSplit: 1, ySplit: 2 }] });
    ws.columns = [{ width: 16 }, { width: 14 }, { width: 10 }, { width: 12 }, { width: 8 }, { width: 12 }];
    ws.mergeCells("A1:D1");
    ws.getCell("A1").value = "Hello workbook summary";
    ws.getRow(2).values = ["Item", "Amount", "Share", "Date", "Time", "Code"];
    const money = '"$"#,##0.00;[Red]-"$"#,##0.00';
    const rows = [["Alpha", 10, 0.1, Date.UTC(2026, 8, 27), 0.5, "00123"], ["Beta", 20, 0.2, Date.UTC(2026, 0, 15), 0.75, "00456"],
      ["Gamma", 30, 0.3, Date.UTC(2025, 11, 31), 0.25, "Hello cell"], ["Delta", -40, 0.4, Date.UTC(2024, 1, 29), 0, "=1+1"]];
    rows.forEach((values, i) => {
      const r = 3 + i;
      ws.getCell(`A${r}`).value = values[0];
      ws.getCell(`B${r}`).value = values[1]; ws.getCell(`B${r}`).numFmt = money;
      ws.getCell(`C${r}`).value = values[2]; ws.getCell(`C${r}`).numFmt = "0.0%";
      ws.getCell(`D${r}`).value = new Date(values[3]); ws.getCell(`D${r}`).numFmt = "yyyy-mm-dd";
      ws.getCell(`E${r}`).value = values[4]; ws.getCell(`E${r}`).numFmt = "hh:mm";
      ws.getCell(`F${r}`).value = values[5];                        // text, including leading zeros and "=1+1"
    });
    ws.getCell("A7").value = "Total";
    ws.getCell("B7").value = { formula: "SUM(B3:B6)", result: 20 }; ws.getCell("B7").numFmt = money;
    ws.getCell("A8").value = "Missing";
    ws.getCell("B8").value = { formula: "B3*2" };                     // no cached result on purpose
    ws.getCell("A9").value = "Web service";
    ws.getCell("B9").value = { formula: `WEBSERVICE("${LISTENER}/xlsx-webservice")`, result: "cached-ok" };
    ws.getCell("A10").value = "External";
    ws.getCell("B10").value = { formula: `'[${WEBDAV_UNC}\\book.xlsx]Sheet1'!A1`, result: 7 };
    ws.getCell("A11").value = "Flags";
    ws.getCell("B11").value = true;
    ws.getCell("C11").value = { error: "#DIV/0!" };
    ws.getCell("A12").value = "Big";
    ws.getCell("B12").value = 1234567.891; ws.getCell("B12").numFmt = "#,##0.00";
    ws.getCell("A13").value = "General";
    ws.getCell("B13").value = 0.1 + 0.2;

    const rtl = wb.addWorksheet("Urdu", { views: [{ rightToLeft: true }] });
    rtl.columns = [{ width: 36 }];
    ["اردو: یہ ایک دستاویز ہے", "سنڌي: سلام دنيا", "العربية: مرحبا بالعالم", "中文：你好世界", "日本語：こんにちは"].forEach((t, i) => { rtl.getCell(`A${i + 1}`).value = t; });

    wb.addWorksheet("HiddenData", { state: "hidden" }).getCell("A1").value = "Secret hidden value";
    wb.addWorksheet("VeryHidden", { state: "veryHidden" }).getCell("A1").value = "Very hidden value";
    write("xlsx/complex.xlsx", await stable(await wb.xlsx.writeBuffer()));
    const cell = (ref, text) => ({ sheet: "Summary", ref, text });
    record({ id: "xlsx-complex", file: "xlsx/complex.xlsx", format: "xlsx", category: "complex", producer, licence,
      expect: {
        result: "open", sheets: ["Summary", "Urdu"], hiddenSheetsNotShown: ["HiddenData", "VeryHidden"], culture: "en-US",
        text: ["Hello workbook summary", "Hello cell"],
        cells: [cell("A1", "Hello workbook summary"), cell("B3", "$10.00"), cell("C3", "10.0%"), cell("D3", "2026-09-27"), cell("E3", "12:00"),
          cell("F3", "00123"), cell("F6", "=1+1"), cell("B6", "-$40.00"), cell("B7", "$20.00"), cell("B8", "Result unavailable"),
          cell("B9", "cached-ok"), cell("B10", "7"), cell("B11", "TRUE"), cell("C11", "#DIV/0!"), cell("B12", "1,234,567.89"), cell("B13", "0.3"),
          { sheet: "Urdu", ref: "A2", text: "سنڌي: سلام دنيا" }],
        merges: [{ sheet: "Summary", range: "A1:D1" }], frozen: { sheet: "Summary", rows: 2, columns: 1 }, rightToLeft: ["Urdu"]
      },
      rules: { ...SAFE_RULES, formulas: "Never recalculated; WEBSERVICE and the external workbook reference must not be contacted" } });
  }

  // Empty worksheet
  {
    const wb = workbook(); wb.addWorksheet("Blank");
    write("xlsx/empty-sheet.xlsx", await stable(await wb.xlsx.writeBuffer()));
    record({ id: "xlsx-empty-sheet", file: "xlsx/empty-sheet.xlsx", format: "xlsx", category: "empty", producer, licence,
      expect: { result: "open", sheets: ["Blank"], notice: "This sheet is empty." }, rules: SAFE_RULES });
  }

  // Password protected (Agile encryption). Test password, not a secret.
  {
    const plain = fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx"));
    write("xlsx/password.xlsx", officeCrypto.encrypt(plain, { password: "viewer-test" }));
    record({ id: "xlsx-password", file: "xlsx/password.xlsx", format: "xlsx", category: "password",
      producer: `${producer}, encrypted with officecrypto-tool ${packageVersion("officecrypto-tool")}`, licence, password: "viewer-test",
      expect: { result: "error", error: "password" }, rules: SAFE_RULES,
      notes: "Without a password: asks for it. Opens with the test password viewer-test (core, worker and smoke tests); a wrong one is refused." });
  }

  // An older binary container (not encrypted) saved with an .xlsx name.
  {
    const container = CFB.utils.cfb_new();
    CFB.utils.cfb_add(container, "Workbook", Buffer.from("Not a real BIFF stream; container only."));
    write("xlsx/old-format-renamed.xlsx", Buffer.from(CFB.write(container, { type: "buffer" })));
    record({ id: "xlsx-old-format", file: "xlsx/old-format-renamed.xlsx", format: "xlsx", category: "wrong-extension", producer: `cfb ${packageVersion("cfb")} (Node)`, licence,
      expect: { result: "error", error: "mismatch" }, rules: SAFE_RULES });
  }

  // Damaged, empty and mislabelled files
  {
    const full = fs.readFileSync(path.join(CORPUS, "xlsx", "complex.xlsx"));
    write("xlsx/damaged-truncated.xlsx", full.subarray(0, Math.floor(full.length * 0.5)));
    record({ id: "xlsx-truncated", file: "xlsx/damaged-truncated.xlsx", format: "xlsx", category: "damaged", producer: `${producer}, then truncated`, licence,
      expect: { result: "error", error: "damaged" }, rules: SAFE_RULES });
    write("xlsx/zero-byte.xlsx", Buffer.alloc(0));
    record({ id: "xlsx-zero-byte", file: "xlsx/zero-byte.xlsx", format: "xlsx", category: "empty", producer: "generator (empty file)", licence,
      expect: { result: "error", error: "empty" }, rules: SAFE_RULES });
    write("xlsx/not-a-workbook.xlsx", "Plain text saved with an .xlsx name.\r\n");
    record({ id: "xlsx-mismatch", file: "xlsx/not-a-workbook.xlsx", format: "xlsx", category: "wrong-extension", producer: "generator (text)", licence,
      expect: { result: "error", error: "mismatch" }, rules: SAFE_RULES });
  }

  // Macro-enabled workbook: opens with its saved values; the macro project is ignored (never read or run).
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    zip.file("xl/vbaProject.bin", Buffer.from("Placeholder, not real VBA."), { date });
    const types = await zip.file("[Content_Types].xml").async("string");
    zip.file("[Content_Types].xml", types.replace("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml", "application/vnd.ms-excel.sheet.macroEnabled.main+xml")
      .replace("</Types>", '<Default Extension="bin" ContentType="application/vnd.ms-office.vbaProject"/></Types>'), { date });
    write("xlsx/macro.xlsm", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "xlsm-macro", file: "xlsx/macro.xlsm", format: "xlsm", category: "macro", producer: `${producer}, repackaged with JSZip`, licence,
      expect: { result: "open", sheets: ["Hello"], cells: [{ sheet: "Hello", ref: "B1", text: "42" }], macrosRemoved: true }, rules: SAFE_RULES });
  }
  // Template: same parts, template main type; opens like an ordinary workbook.
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    const types = await zip.file("[Content_Types].xml").async("string");
    zip.file("[Content_Types].xml", types.replace("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml", "application/vnd.openxmlformats-officedocument.spreadsheetml.template.main+xml"), { date });
    write("xlsx/variant.xltx", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "xltx-variant", file: "xlsx/variant.xltx", format: "xltx", category: "variant", producer: `${producer}, repackaged with JSZip`, licence,
      expect: { result: "open", sheets: ["Hello"], cells: [{ sheet: "Hello", ref: "B1", text: "42" }] }, rules: SAFE_RULES });
  }

  // Hostile: ZIP bomb (an extra 300 MB entry of zeros, about 300 KB compressed).
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    zip.file("xl/media/bomb.bin", Buffer.alloc(300 * 1024 * 1024), { date, compression: "DEFLATE", compressionOptions: { level: 9 } });
    zip.forEach((_, f) => { f.date = date; });
    write("xlsx/attack-zip-bomb.xlsx", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "attack-xlsx-zip-bomb", file: "xlsx/attack-zip-bomb.xlsx", format: "xlsx", category: "attack", producer: `${producer}, repackaged with JSZip`, licence,
      expect: { result: "error", error: "damaged" }, rules: SAFE_RULES, notes: "Must be refused by the archive limits without decompressing the 300 MB entry." });
  }

  // Hostile: XML external entity in the workbook part.
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "simple.xlsx")));
    const workbookXml = await zip.file("xl/workbook.xml").async("string");
    const doctype = `<!DOCTYPE workbook [<!ENTITY remote SYSTEM "${LISTENER}/xlsx-xxe/entity"><!ENTITY local SYSTEM "file:///C:/Windows/win.ini">]>`;
    zip.file("xl/workbook.xml", workbookXml.replace(/^(<\?xml[^>]*\?>)/, `$1${doctype}`).replace('name="Hello"', 'name="&remote;&local;"'), { date });
    write("xlsx/attack-xxe.xlsx", await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    record({ id: "attack-xlsx-xxe", file: "xlsx/attack-xxe.xlsx", format: "xlsx", category: "attack", producer: `${producer}, edited with JSZip`, licence,
      expect: { result: "error", error: "damaged" }, rules: SAFE_RULES, notes: "DTDs are prohibited; neither entity may be resolved." });
  }

  // Pictures and charts: a picture placed by exceljs, then two charts on the same sheet and a chart sheet added as
  // hand-written DrawingML (exceljs cannot write charts). Chart values are the chart's own cache.
  {
    const wb = workbook();
    const ws = wb.addWorksheet("Sales");
    ws.addRows([["Month", "North", "South"], ["Jan", 120, 80], ["Feb", 150, 95], ["Mar", 90, 130], ["Apr", 170, 110]]);
    ws.getCell("A7").value = "Hello pictures";
    const image = wb.addImage({ buffer: chartPng(), extension: "png" });
    ws.addImage(image, { tl: { col: 4, row: 0 }, ext: { width: 240, height: 120 }, editAs: "oneCell" });
    const zip = await JSZip.loadAsync(await wb.xlsx.writeBuffer());
    const drawingPath = Object.keys(zip.files).find(n => /^xl\/drawings\/drawing\d+\.xml$/.test(n));
    const relsPath = drawingPath.replace("drawings/", "drawings/_rels/") + ".rels";
    const frame = (id, from, to, rid, name) => `<xdr:twoCellAnchor><xdr:from><xdr:col>${from[0]}</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${from[1]}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from>` +
      `<xdr:to><xdr:col>${to[0]}</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${to[1]}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to>` +
      `<xdr:graphicFrame macro=""><xdr:nvGraphicFramePr><xdr:cNvPr id="${id}" name="${name}"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/></xdr:xfrm>` +
      `<a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:id="${rid}"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:twoCellAnchor>`;
    let drawing = await zip.file(drawingPath).async("string");
    if (!drawing.includes('xmlns:a=')) drawing = drawing.replace("<xdr:wsDr ", '<xdr:wsDr xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ');
    drawing = drawing.replace("</xdr:wsDr>", frame(10, [0, 8], [5, 22], "rIdChart1", "Sales by month") + frame(11, [6, 8], [11, 22], "rIdChart2", "January share") + "</xdr:wsDr>");
    zip.file(drawingPath, drawing);
    const chartRel = (id, n) => `<Relationship Id="${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart" Target="../charts/chart${n}.xml"/>`;
    zip.file(relsPath, (await zip.file(relsPath).async("string")).replace("</Relationships>", chartRel("rIdChart1", 1) + chartRel("rIdChart2", 2) + "</Relationships>"));
    const months = ["Jan", "Feb", "Mar", "Apr"];
    zip.file("xl/charts/chart1.xml", chartXml({ kind: "barChart", title: "Sales by month", categories: months, series: [["North", [120, 150, 90, 170], "4472C4"], ["South", [80, 95, 130, 110], "ED7D31"]],
      labels: ["value"], axisTitles: { cat: "Month", val: "Units sold" } }));
    zip.file("xl/charts/chart2.xml", chartXml({ kind: "pieChart", title: "January share", categories: ["North", "South"], series: [["January", [120, 80]]], across: { cat: "Sales!$B$1:$C$1", val: "Sales!$B$2:$C$2" },
      labels: ["category", "percent"] }));
    zip.file("xl/charts/chart3.xml", chartXml({ kind: "lineChart", title: "Trend", categories: months, series: [["North", [120, 150, 90, 170], "70AD47"], ["South", [80, 95, 130, 110]]] }));
    // The chart sheet "Trend".
    zip.file("xl/chartsheets/sheet2.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><chartsheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetPr/><sheetViews><sheetView workbookViewId="0"/></sheetViews><pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/><drawing r:id="rId1"/></chartsheet>`);
    zip.file("xl/chartsheets/_rels/sheet2.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing90.xml"/></Relationships>`);
    zip.file("xl/drawings/drawing90.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
      `<xdr:absoluteAnchor><xdr:pos x="0" y="0"/><xdr:ext cx="8666667" cy="6293304"/><xdr:graphicFrame macro=""><xdr:nvGraphicFramePr><xdr:cNvPr id="2" name="Trend"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/></xdr:xfrm>` +
      `<a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" r:id="rId1"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:absoluteAnchor></xdr:wsDr>`);
    zip.file("xl/drawings/_rels/drawing90.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${chartRel("rId1", 3)}</Relationships>`);
    let book = await zip.file("xl/workbook.xml").async("string");
    book = book.replace("</sheets>", '<sheet name="Trend" sheetId="90" r:id="rIdChartSheet"/></sheets>');
    zip.file("xl/workbook.xml", book);
    zip.file("xl/_rels/workbook.xml.rels", (await zip.file("xl/_rels/workbook.xml.rels").async("string")).replace("</Relationships>",
      '<Relationship Id="rIdChartSheet" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/chartsheet" Target="chartsheets/sheet2.xml"/></Relationships>'));
    const override = (part, type) => `<Override PartName="/${part}" ContentType="application/vnd.openxmlformats-officedocument.${type}"/>`;
    zip.file("[Content_Types].xml", (await zip.file("[Content_Types].xml").async("string")).replace("</Types>",
      override("xl/charts/chart1.xml", "drawingml.chart+xml") + override("xl/charts/chart2.xml", "drawingml.chart+xml") + override("xl/charts/chart3.xml", "drawingml.chart+xml") +
      override("xl/chartsheets/sheet2.xml", "spreadsheetml.chartsheet+xml") + override("xl/drawings/drawing90.xml", "drawing+xml") + "</Types>"));
    write("xlsx/drawings.xlsx", await stable(await zip.generateAsync({ type: "nodebuffer" })));
    record({ id: "xlsx-drawings", file: "xlsx/drawings.xlsx", format: "xlsx", category: "complex", producer: `${producer}, charts added as hand-written DrawingML with JSZip`, licence,
      expect: { result: "open", sheets: ["Sales", "Trend"], text: ["Hello pictures"],
        drawings: [{ sheet: "Sales", pictures: 1, charts: ["column:Sales by month:2", "pie:January share:1"], values: ["120,150,90,170", "80,95,130,110"], categories: "Jan,Feb,Mar,Apr",
          titles: "Month|Units sold", labels: "120|150|90|170", values2: ["120,80"], categories2: "North,South", titles2: "|", labels2: "North, 60%|South, 40%" },
          { sheet: "Trend", chartSheet: true, charts: ["line:Trend:2"], titles: "|", labels: "" }] },
      rules: SAFE_RULES, notes: "The picture is the corpus's own PNG. Charts are drawn from their cached values; the chart sheet shows its chart filling the view." });
  }

  // Shapes and text boxes, hand-written DrawingML (exceljs cannot write shapes): a text box, shapes coloured through
  // their style's theme references, a dashed outline, an arrow line, a block arrow, a star (drawn as a rectangle) and
  // a group (counted, not shown).
  {
    const wb = workbook();
    const ws = wb.addWorksheet("Notes");
    ws.getCell("A1").value = "Hello shapes";
    const zip = await JSZip.loadAsync(await wb.xlsx.writeBuffer());
    const anchor = (from, to, body) => `<xdr:twoCellAnchor><xdr:from><xdr:col>${from[0]}</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${from[1]}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from>` +
      `<xdr:to><xdr:col>${to[0]}</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${to[1]}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to>${body}<xdr:clientData/></xdr:twoCellAnchor>`;
    const geometry = prst => `<a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/></a:xfrm><a:prstGeom prst="${prst}"><a:avLst/></a:prstGeom>`;
    const sp = (id, name, prst, look, extra = "", box = false) => `<xdr:sp macro="" textlink=""><xdr:nvSpPr><xdr:cNvPr id="${id}" name="${name}"/><xdr:cNvSpPr${box ? ' txBox="1"' : ""}/></xdr:nvSpPr>` +
      `<xdr:spPr>${geometry(prst)}${look}</xdr:spPr>${extra}</xdr:sp>`;
    const paragraph = (text, size, attributes = "", align = "") => `<a:p>${align ? `<a:pPr algn="${align}"/>` : ""}<a:r><a:rPr lang="en-US" sz="${size}"${attributes}/><a:t>${text}</a:t></a:r></a:p>`;
    const body = (anchorAt, paragraphs) => `<xdr:txBody><a:bodyPr vertOverflow="clip" wrap="square" rtlCol="0" anchor="${anchorAt}"/><a:lstStyle/>${paragraphs}</xdr:txBody>`;
    // A shape inside the group, at [x, y, cx, cy] in the group's child coordinates.
    const groupChild = (id, text, prst, [x, y, cx, cy], colour) => `<xdr:sp macro="" textlink=""><xdr:nvSpPr><xdr:cNvPr id="${id}" name="${text}"/><xdr:cNvSpPr/></xdr:nvSpPr>` +
      `<xdr:spPr><a:xfrm><a:off x="${x}" y="${y}"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="${prst}"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="${colour}"/></a:solidFill></xdr:spPr>` +
      `<xdr:txBody><a:bodyPr anchor="ctr"/><a:lstStyle/><a:p><a:pPr algn="ctr"/><a:r><a:rPr lang="en-US" sz="1100"/><a:t>${text}</a:t></a:r></a:p></xdr:txBody></xdr:sp>`;
    const themed = `<xdr:style><a:lnRef idx="2"><a:schemeClr val="accent1"><a:shade val="50000"/></a:schemeClr></a:lnRef><a:fillRef idx="1"><a:schemeClr val="accent1"/></a:fillRef>` +
      `<a:effectRef idx="0"><a:schemeClr val="accent1"/></a:effectRef><a:fontRef idx="minor"><a:schemeClr val="lt1"/></a:fontRef></xdr:style>`;
    const shapes =
      anchor([1, 1], [5, 6], sp(2, "Note", "rect", '<a:solidFill><a:schemeClr val="lt1"/></a:solidFill><a:ln w="9525" cmpd="sng"><a:solidFill><a:schemeClr val="lt1"><a:shade val="50000"/></a:schemeClr></a:solidFill></a:ln>',
        body("t", paragraph("Hello shapes", 1400, ' b="1"') + paragraph("A read-only note", 1100)), true)) +
      anchor([6, 1], [9, 4], sp(3, "Approved", "roundRect", "", themed + body("ctr", paragraph("Approved", 1200, "", "ctr")))) +
      anchor([6, 5], [8, 9], sp(4, "Circle", "ellipse", '<a:noFill/><a:ln w="19050"><a:solidFill><a:srgbClr val="C00000"/></a:solidFill><a:prstDash val="dash"/></a:ln>')) +
      anchor([1, 7], [5, 10], `<xdr:cxnSp macro=""><xdr:nvCxnSpPr><xdr:cNvPr id="5" name="Arrow"/><xdr:cNvCxnSpPr/></xdr:nvCxnSpPr><xdr:spPr>${geometry("straightConnector1")}` +
        '<a:ln w="19050"><a:solidFill><a:srgbClr val="000000"/></a:solidFill><a:tailEnd type="triangle"/></a:ln></xdr:spPr></xdr:cxnSp>') +
      anchor([1, 11], [4, 14], sp(6, "Next", "rightArrow", '<a:solidFill><a:srgbClr val="70AD47"/></a:solidFill><a:ln><a:noFill/></a:ln>', body("ctr", paragraph("Next", 1100, "", "ctr")))) +
      anchor([6, 11], [8, 15], sp(7, "Star", "star5", '<a:solidFill><a:srgbClr val="FFC000"/></a:solidFill>')) +
      anchor([10, 1], [14, 6], `<xdr:grpSp><xdr:nvGrpSpPr><xdr:cNvPr id="8" name="Group"/><xdr:cNvGrpSpPr/></xdr:nvGrpSpPr>` +
        `<xdr:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="2000000" cy="1000000"/><a:chOff x="1000000" y="500000"/><a:chExt cx="2000000" cy="1000000"/></a:xfrm></xdr:grpSpPr>` +
        groupChild(9, "Step 1", "rect", [1000000, 500000, 1000000, 1000000], "5B9BD5") + groupChild(10, "Step 2", "ellipse", [2000000, 500000, 1000000, 500000], "FFC000") + `</xdr:grpSp>`);
    zip.file("xl/drawings/drawing1.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">${shapes}</xdr:wsDr>`);
    zip.file("xl/worksheets/_rels/sheet1.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdDrawing" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/></Relationships>`);
    const sheetXml = await zip.file("xl/worksheets/sheet1.xml").async("string");
    if (!sheetXml.includes("xmlns:r=")) throw new Error("shapes.xlsx: worksheet has no r namespace");
    zip.file("xl/worksheets/sheet1.xml", sheetXml.replace("</worksheet>", '<drawing r:id="rIdDrawing"/></worksheet>'));
    zip.file("[Content_Types].xml", (await zip.file("[Content_Types].xml").async("string")).replace("</Types>",
      '<Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/></Types>'));
    write("xlsx/shapes.xlsx", await stable(await zip.generateAsync({ type: "nodebuffer" })));
    record({ id: "xlsx-shapes", file: "xlsx/shapes.xlsx", format: "xlsx", category: "complex", producer: `${producer}, shapes added as hand-written DrawingML with JSZip`, licence,
      expect: { result: "open", sheets: ["Notes"], text: ["Hello shapes"],
        drawings: [{ sheet: "Notes", pictures: 0, shapes: ["rect:#ffffff:#bcbcbc:Hello shapes/A read-only note", "roundRect:#4f81bd:#385d8a:Approved", "ellipse:-:#c00000:",
          "line:-:#000000:", "rightArrow:#70ad47:-:Next", "rect:#ffc000:-:", "rect:#5b9bd5:-:Step 1", "ellipse:#ffc000:-:Step 2"],
          parts: ["0,0,0.5,1", "0.5,0,0.5,0.5"] }] },
      rules: SAFE_RULES, notes: "Theme colours from exceljs's Office theme (accent1 #4f81bd; the rounded rectangle's outline is accent1 at 50% shade). The star is drawn as a rectangle. The group maps child coordinates (offset 1,000,000/500,000, size 2,000,000 x 1,000,000) onto its anchor: Step 1 fills its left half, Step 2 the top of its right half." });
  }

  // Hostile: a linked picture (stored outside the file) pointing at the request listener and at a network share.
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "drawings.xlsx")));
    const drawingPath = Object.keys(zip.files).find(n => /^xl\/drawings\/drawing\d\.xml$/.test(n));
    const relsPath = drawingPath.replace("drawings/", "drawings/_rels/") + ".rels";
    const pic = (id, rid) => `<xdr:oneCellAnchor><xdr:from><xdr:col>1</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${id}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:ext cx="952500" cy="476250"/>` +
      `<xdr:pic><xdr:nvPicPr><xdr:cNvPr id="${id}" name="Linked ${id}"/><xdr:cNvPicPr/></xdr:nvPicPr><xdr:blipFill><a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:link="${rid}"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill>` +
      `<xdr:spPr><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor>`;
    zip.file(drawingPath, (await zip.file(drawingPath).async("string")).replace("</xdr:wsDr>", pic(30, "rIdLink1") + pic(31, "rIdLink2") + "</xdr:wsDr>"));
    const link = (id, target) => `<Relationship Id="${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="${target}" TargetMode="External"/>`;
    zip.file(relsPath, (await zip.file(relsPath).async("string")).replace("</Relationships>",
      link("rIdLink1", `${LISTENER}/xlsx-linked-picture/image.png`) + link("rIdLink2", `file:///${WEBDAV_UNC.replace(/\\/g, "/")}/image.png`) + "</Relationships>"));
    write("xlsx/attack-linked-picture.xlsx", await stable(await zip.generateAsync({ type: "nodebuffer" })));
    record({ id: "attack-xlsx-linked-picture", file: "xlsx/attack-linked-picture.xlsx", format: "xlsx", category: "attack", producer: `${producer}, edited with JSZip`, licence,
      expect: { result: "open", sheets: ["Sales", "Trend"], text: ["Hello pictures", "linked picture"], drawings: [{ sheet: "Sales", pictures: 1 }] },
      rules: SAFE_RULES, notes: "Two linked pictures (web address and network share) must never be fetched; the notice says they are not loaded." });
  }

  // More chart kinds (after 0.9.0): the pictures workbook with its charts replaced by columns with a line over them, a
  // filled radar chart, a stock chart (the chart sheet) and a fourth chart, a bubble chart. Hand-written DrawingML.
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "drawings.xlsx")));
    const head = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><c:chart>`;
    const title = text => `<c:title><c:tx><c:rich><a:bodyPr/><a:p><a:r><a:t>${text}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title><c:autoTitleDeleted val="0"/>`;
    const tail = `<c:legend><c:legendPos val="b"/><c:overlay val="0"/></c:legend><c:plotVisOnly val="1"/></c:chart></c:chartSpace>`;
    const str = values => `<c:strCache><c:ptCount val="${values.length}"/>${values.map((v, i) => `<c:pt idx="${i}"><c:v>${v}</c:v></c:pt>`).join("")}</c:strCache>`;
    const num = values => `<c:numCache><c:formatCode>General</c:formatCode><c:ptCount val="${values.length}"/>${values.map((v, i) => `<c:pt idx="${i}"><c:v>${v}</c:v></c:pt>`).join("")}</c:numCache>`;
    const months = ["Jan", "Feb", "Mar", "Apr"];
    const ser = (i, name, values, categories = months, colour) => `<c:ser><c:idx val="${i}"/><c:order val="${i}"/><c:tx><c:strRef><c:f>Sales!$A$${i + 1}</c:f>${str([name])}</c:strRef></c:tx>` +
      (colour ? `<c:spPr><a:solidFill><a:srgbClr val="${colour}"/></a:solidFill></c:spPr>` : "") +
      `<c:cat><c:strRef><c:f>Sales!$A$2:$A$5</c:f>${str(categories)}</c:strRef></c:cat><c:val><c:numRef><c:f>Sales!$B$2:$B$5</c:f>${num(values)}</c:numRef></c:val></c:ser>`;
    const axes = `<c:catAx><c:axId val="1"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="b"/><c:crossAx val="2"/></c:catAx><c:valAx><c:axId val="2"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="l"/><c:majorGridlines/><c:crossAx val="1"/></c:valAx>`;
    zip.file("xl/charts/chart1.xml", head + title("Sales and target") + `<c:plotArea><c:layout/><c:barChart><c:barDir val="col"/><c:grouping val="clustered"/><c:varyColors val="0"/>${ser(0, "North", [120, 150, 90, 170])}<c:axId val="1"/><c:axId val="2"/></c:barChart>` +
      `<c:lineChart><c:grouping val="standard"/><c:varyColors val="0"/>${ser(1, "Target", [130, 130, 130, 130], months, "C00000")}<c:marker val="1"/><c:axId val="1"/><c:axId val="2"/></c:lineChart>${axes}</c:plotArea>` + tail);
    zip.file("xl/charts/chart2.xml", head + title("Skills") + `<c:plotArea><c:layout/><c:radarChart><c:radarStyle val="filled"/><c:varyColors val="0"/>` +
      ser(0, "Team A", [4, 3, 5, 2, 4], ["Design", "Code", "Test", "Docs", "Support"]) + ser(1, "Team B", [3, 5, 2, 4, 3], ["Design", "Code", "Test", "Docs", "Support"]) + `<c:axId val="1"/><c:axId val="2"/></c:radarChart>${axes}</c:plotArea>` + tail);
    zip.file("xl/charts/chart3.xml", head + title("Share price") + `<c:plotArea><c:layout/><c:stockChart>${ser(0, "High", [52, 55, 54, 58])}${ser(1, "Low", [47, 49, 48, 51])}${ser(2, "Close", [50, 53, 49, 57])}<c:hiLowLines/><c:axId val="1"/><c:axId val="2"/></c:stockChart>${axes}</c:plotArea>` + tail);
    const bubbleSer = (i, name, xs, ys, sizes) => `<c:ser><c:idx val="${i}"/><c:order val="${i}"/><c:tx><c:strRef><c:f>Sales!$A$1</c:f>${str([name])}</c:strRef></c:tx>` +
      `<c:xVal><c:numRef><c:f>Sales!$B$2:$B$4</c:f>${num(xs)}</c:numRef></c:xVal><c:yVal><c:numRef><c:f>Sales!$C$2:$C$4</c:f>${num(ys)}</c:numRef></c:yVal><c:bubbleSize><c:numRef><c:f>Sales!$D$2:$D$4</c:f>${num(sizes)}</c:numRef></c:bubbleSize><c:bubble3D val="0"/></c:ser>`;
    zip.file("xl/charts/chart4.xml", head + title("Markets") + `<c:plotArea><c:layout/><c:bubbleChart><c:varyColors val="0"/>${bubbleSer(0, "Products", [1, 3, 5], [20, 35, 15], [10, 40, 25])}<c:bubbleScale val="100"/><c:axId val="1"/><c:axId val="2"/></c:bubbleChart>` +
      `<c:valAx><c:axId val="1"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="b"/><c:crossAx val="2"/></c:valAx><c:valAx><c:axId val="2"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:delete val="0"/><c:axPos val="l"/><c:crossAx val="1"/></c:valAx></c:plotArea>` + tail);
    // The fourth chart: a copy of the second chart's frame, lower down, pointing at chart4.
    const drawingPath = "xl/drawings/drawing1.xml", relsPath = "xl/drawings/_rels/drawing1.xml.rels";
    const drawing = await zip.file(drawingPath).async("string");
    const anchors = drawing.match(/<xdr:twoCellAnchor[\s\S]*?<\/xdr:twoCellAnchor>/g) ?? [];
    const second = anchors.find(a => a.includes("graphicFrame") && a !== anchors.find(b => b.includes("graphicFrame")));
    const copy = second.replace(/<xdr:row>(\d+)<\/xdr:row>/g, (_, r) => `<xdr:row>${+r + 16}</xdr:row>`).replace(/r:id="[^"]+"/, 'r:id="rIdChart4"').replace(/name="[^"]*"/, 'name="Chart 4"').replace(/ id="\d+"/, ' id="44"');
    zip.file(drawingPath, drawing.replace("</xdr:wsDr>", copy + "</xdr:wsDr>"));
    zip.file(relsPath, (await zip.file(relsPath).async("string")).replace("</Relationships>",
      `<Relationship Id="rIdChart4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart" Target="../charts/chart4.xml"/></Relationships>`));
    zip.file("[Content_Types].xml", (await zip.file("[Content_Types].xml").async("string")).replace("</Types>",
      `<Override PartName="/xl/charts/chart4.xml" ContentType="application/vnd.openxmlformats-officedocument.drawingml.chart+xml"/></Types>`));
    write("xlsx/charts-more.xlsx", await stable(await zip.generateAsync({ type: "nodebuffer" })));
    record({ id: "xlsx-charts-more", file: "xlsx/charts-more.xlsx", format: "xlsx", category: "complex", producer: `${producer}, charts as hand-written DrawingML with JSZip`, licence,
      expect: { result: "open", sheets: ["Sales", "Trend"], text: ["Hello pictures"],
        drawings: [{ sheet: "Sales", pictures: 1, charts: ["column:Sales and target:2", "radar:Skills:2", "bubble:Markets:1"] }, { sheet: "Trend", pictures: 0, charts: ["stock:Share price:3"], chartSheet: true }] }, rules: SAFE_RULES,
      notes: "Columns with a line series over them (a combined chart), a filled radar chart, a bubble chart and a stock chart (high, low, close)." });
  }

  // SmartArt (after 0.9.0): the shapes workbook with a basic process diagram added, written by hand the way Excel stores
  // one: data, layout, style and colour parts, plus the drawn copy of the diagram (diagrams/drawing1.xml) that the
  // viewer shows. Proves the reader, not fidelity to Excel's own layout.
  {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "shapes.xlsx")));
    const drawingPath = "xl/drawings/drawing1.xml", relsPath = "xl/drawings/_rels/drawing1.xml.rels";
    const R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";
    const rel = (id, type, target) => `<Relationship Id="${id}" Type="${type}" Target="${target}"/>`;
    const rels = (zip.file(relsPath) ? await zip.file(relsPath).async("string") : `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>`)
      .replace("</Relationships>", rel("rIdDm", `${R}/diagramData`, "../diagrams/data1.xml") + rel("rIdLo", `${R}/diagramLayout`, "../diagrams/layout1.xml") +
        rel("rIdQs", `${R}/diagramQuickStyle`, "../diagrams/quickStyle1.xml") + rel("rIdCs", `${R}/diagramColors`, "../diagrams/colors1.xml") +
        rel("rIdDd", "http://schemas.microsoft.com/office/2007/relationships/diagramDrawing", "../diagrams/drawing1.xml") + "</Relationships>");
    zip.file(relsPath, rels);
    const frame = `<xdr:twoCellAnchor><xdr:from><xdr:col>1</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>20</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:to><xdr:col>7</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>26</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to>` +
      `<xdr:graphicFrame macro=""><xdr:nvGraphicFramePr><xdr:cNvPr id="60" name="Diagram 1"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm><a:off x="0" y="0"/><a:ext cx="3657600" cy="1143000"/></xdr:xfrm>` +
      `<a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/diagram"><dgm:relIds xmlns:dgm="http://schemas.openxmlformats.org/drawingml/2006/diagram" xmlns:r="${R}" r:dm="rIdDm" r:lo="rIdLo" r:qs="rIdQs" r:cs="rIdCs"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:twoCellAnchor>`;
    zip.file(drawingPath, (await zip.file(drawingPath).async("string")).replace("</xdr:wsDr>", frame + "</xdr:wsDr>"));
    const dgm = `xmlns:dgm="http://schemas.openxmlformats.org/drawingml/2006/diagram" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"`;
    const steps = ["Plan", "Build", "Hello SmartArt"];
    zip.file("xl/diagrams/data1.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><dgm:dataModel ${dgm} xmlns:dsp="http://schemas.microsoft.com/office/drawing/2008/diagram"><dgm:ptLst>` +
      `<dgm:pt modelId="{00000000-0000-0000-0000-000000000000}" type="doc"><dgm:prSet/><dgm:spPr/><dgm:t><a:bodyPr/><a:p><a:endParaRPr/></a:p></dgm:t></dgm:pt>` +
      steps.map((s, i) => `<dgm:pt modelId="{00000000-0000-0000-0000-00000000000${i + 1}}"><dgm:prSet/><dgm:spPr/><dgm:t><a:bodyPr/><a:p><a:r><a:t>${s}</a:t></a:r></a:p></dgm:t></dgm:pt>`).join("") +
      `</dgm:ptLst><dgm:cxnLst/><dgm:bg/><dgm:whole/><dgm:extLst><a:ext uri="http://schemas.microsoft.com/office/drawing/2008/diagram"><dsp:dataModelExt relId="rIdDd" minVer="http://schemas.openxmlformats.org/drawingml/2006/diagram"/></a:ext></dgm:extLst></dgm:dataModel>`);
    zip.file("xl/diagrams/layout1.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><dgm:layoutDef ${dgm} uniqueId="urn:microsoft.com/office/officeart/2005/8/layout/process1"><dgm:title val=""/><dgm:desc val=""/><dgm:layoutNode name="Name0"/></dgm:layoutDef>`);
    zip.file("xl/diagrams/quickStyle1.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><dgm:styleDef ${dgm} uniqueId="urn:microsoft.com/office/officeart/2005/8/quickstyle/simple1"><dgm:title val=""/><dgm:desc val=""/></dgm:styleDef>`);
    zip.file("xl/diagrams/colors1.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><dgm:colorsDef ${dgm} uniqueId="urn:microsoft.com/office/officeart/2005/8/colors/accent1_2"><dgm:title val=""/><dgm:desc val=""/></dgm:colorsDef>`);
    // The drawn copy: three rounded boxes and two arrows across the frame (3,657,600 by 1,143,000 EMU).
    const box = (id, x, text) => `<dsp:sp modelId="{10000000-0000-0000-0000-00000000000${id}}"><dsp:nvSpPr><dsp:cNvPr id="0" name=""/><dsp:cNvSpPr/></dsp:nvSpPr>` +
      `<dsp:spPr><a:xfrm><a:off x="${x}" y="228600"/><a:ext cx="914400" cy="685800"/></a:xfrm><a:prstGeom prst="roundRect"><a:avLst/></a:prstGeom><a:solidFill><a:schemeClr val="accent1"/></a:solidFill><a:ln w="12700"><a:solidFill><a:schemeClr val="lt1"/></a:solidFill></a:ln></dsp:spPr>` +
      `<dsp:style><a:lnRef idx="2"><a:scrgbClr r="0" g="0" b="0"/></a:lnRef><a:fillRef idx="1"><a:scrgbClr r="0" g="0" b="0"/></a:fillRef><a:effectRef idx="0"><a:scrgbClr r="0" g="0" b="0"/></a:effectRef><a:fontRef idx="minor"><a:schemeClr val="lt1"/></a:fontRef></dsp:style>` +
      `<dsp:txBody><a:bodyPr anchor="ctr"/><a:lstStyle/><a:p><a:pPr algn="ctr"/><a:r><a:rPr lang="en-US" sz="1400"/><a:t>${text}</a:t></a:r></a:p></dsp:txBody><dsp:txXfrm><a:off x="${x}" y="228600"/><a:ext cx="914400" cy="685800"/></dsp:txXfrm></dsp:sp>`;
    const arrow = (id, x) => `<dsp:sp modelId="{20000000-0000-0000-0000-00000000000${id}}"><dsp:nvSpPr><dsp:cNvPr id="0" name=""/><dsp:cNvSpPr/></dsp:nvSpPr>` +
      `<dsp:spPr><a:xfrm><a:off x="${x}" y="457200"/><a:ext cx="365760" cy="228600"/></a:xfrm><a:prstGeom prst="rightArrow"><a:avLst/></a:prstGeom><a:solidFill><a:schemeClr val="accent1"><a:tint val="60000"/></a:schemeClr></a:solidFill></dsp:spPr>` +
      `<dsp:style><a:lnRef idx="0"><a:scrgbClr r="0" g="0" b="0"/></a:lnRef><a:fillRef idx="1"><a:scrgbClr r="0" g="0" b="0"/></a:fillRef><a:effectRef idx="0"><a:scrgbClr r="0" g="0" b="0"/></a:effectRef><a:fontRef idx="minor"><a:schemeClr val="lt1"/></a:fontRef></dsp:style><dsp:txBody><a:bodyPr/><a:lstStyle/><a:p><a:endParaRPr lang="en-US"/></a:p></dsp:txBody></dsp:sp>`;
    zip.file("xl/diagrams/drawing1.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><dsp:drawing xmlns:dgm="http://schemas.openxmlformats.org/drawingml/2006/diagram" xmlns:dsp="http://schemas.microsoft.com/office/drawing/2008/diagram" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">` +
      `<dsp:spTree><dsp:nvGrpSpPr><dsp:cNvPr id="0" name=""/><dsp:cNvGrpSpPr/></dsp:nvGrpSpPr><dsp:grpSpPr/>` +
      box(1, 0, steps[0]) + arrow(1, 1005840) + box(2, 1463040, steps[1]) + arrow(2, 2468880) + box(3, 2743200, steps[2]) + `</dsp:spTree></dsp:drawing>`);
    const types = await zip.file("[Content_Types].xml").async("string");
    const override = (part, type) => `<Override PartName="${part}" ContentType="${type}"/>`;
    zip.file("[Content_Types].xml", types.replace("</Types>",
      override("/xl/diagrams/data1.xml", "application/vnd.openxmlformats-officedocument.drawingml.diagramData+xml") +
      override("/xl/diagrams/layout1.xml", "application/vnd.openxmlformats-officedocument.drawingml.diagramLayout+xml") +
      override("/xl/diagrams/quickStyle1.xml", "application/vnd.openxmlformats-officedocument.drawingml.diagramStyle+xml") +
      override("/xl/diagrams/colors1.xml", "application/vnd.openxmlformats-officedocument.drawingml.diagramColors+xml") +
      override("/xl/diagrams/drawing1.xml", "application/vnd.ms-office.drawingml.diagramDrawing+xml") + "</Types>"));
    write("xlsx/smartart.xlsx", await stable(await zip.generateAsync({ type: "nodebuffer" })));
    record({ id: "xlsx-smartart", file: "xlsx/smartart.xlsx", format: "xlsx", category: "complex", producer: `${producer}, SmartArt parts written by hand with JSZip`, licence,
      expect: { result: "open", sheets: ["Notes"], text: ["Hello shapes"], drawings: [{ sheet: "Notes", pictures: 0, shapesAtLeast: 13, shapeTexts: ["Plan", "Build", "Hello SmartArt"] }] }, rules: SAFE_RULES,
      notes: "A basic process diagram: its drawn copy (three boxes, two arrows) is shown as shapes in the diagram's frame." });
  }

  // Windows metafiles (after 0.9.0): the pictures workbook with its picture replaced by an EMF and a second picture, a
  // WMF, both drawn by LibreOffice from images/complex.svg (scripts/make-legacy-office.ps1 makes them first).
  if (fs.existsSync(path.join(CORPUS, "media", "drawing.emf")) && fs.existsSync(path.join(CORPUS, "media", "drawing.wmf"))) {
    const zip = await JSZip.loadAsync(fs.readFileSync(path.join(CORPUS, "xlsx", "drawings.xlsx")));
    const drawingPath = Object.keys(zip.files).find(n => /^xl\/drawings\/drawing\d\.xml$/.test(n));
    const relsPath = drawingPath.replace("drawings/", "drawings/_rels/") + ".rels";
    const media = Object.keys(zip.files).find(n => /^xl\/media\/image\d+\.png$/.test(n));
    zip.remove(media);
    zip.file(media.replace(/\.png$/, ".emf"), fs.readFileSync(path.join(CORPUS, "media", "drawing.emf")));
    zip.file("xl/media/drawing2.wmf", fs.readFileSync(path.join(CORPUS, "media", "drawing.wmf")));
    const name = media.split("/").pop();
    zip.file(relsPath, (await zip.file(relsPath).async("string")).replace(name, name.replace(/\.png$/, ".emf"))
      .replace("</Relationships>", `<Relationship Id="rIdWmf" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/drawing2.wmf"/></Relationships>`));
    const pic = `<xdr:oneCellAnchor><xdr:from><xdr:col>1</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>30</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:ext cx="1905000" cy="1190625"/>` +
      `<xdr:pic><xdr:nvPicPr><xdr:cNvPr id="40" name="WMF picture"/><xdr:cNvPicPr/></xdr:nvPicPr><xdr:blipFill><a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:embed="rIdWmf"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill>` +
      `<xdr:spPr><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor>`;
    zip.file(drawingPath, (await zip.file(drawingPath).async("string")).replace("</xdr:wsDr>", pic + "</xdr:wsDr>"));
    zip.file("[Content_Types].xml", (await zip.file("[Content_Types].xml").async("string")).replace("<Default ",
      '<Default Extension="emf" ContentType="image/x-emf"/><Default Extension="wmf" ContentType="image/x-wmf"/><Default '));
    write("xlsx/metafiles.xlsx", await stable(await zip.generateAsync({ type: "nodebuffer" })));
    record({ id: "xlsx-metafiles", file: "xlsx/metafiles.xlsx", format: "xlsx", category: "complex", producer: `${producer}, EMF and WMF pictures by LibreOffice 26.2.6 from images/complex.svg, placed with JSZip`, licence,
      expect: { result: "open", sheets: ["Sales", "Trend"], text: ["Hello pictures"], drawings: [{ sheet: "Sales", pictures: 2 }] }, rules: SAFE_RULES,
      notes: "An EMF and a WMF picture: both are drawn into PNGs by the worker and shown." });
  }

  if (large) {
    const target = path.join(CORPUS, "generated", "xlsx-large-500k-rows.xlsx");
    fs.mkdirSync(path.dirname(target), { recursive: true });
    const wb = new ExcelJS.stream.xlsx.WorkbookWriter({ filename: target, useSharedStrings: false, useStyles: true });
    const ws = wb.addWorksheet("Large");
    ws.addRow(["Row", "Region", "Amount", "Share", "Code", "Note"]).commit();
    const regions = ["North", "South", "East", "West", "Sindh"];
    for (let i = 1; i <= 500000; i++) ws.addRow([i, regions[i % 5], (i * 7919) % 100000 / 100, (i % 1000) / 1000, String(i).padStart(8, "0"), i === 500000 ? "Hello last row" : `note ${i % 97}`]).commit();
    ws.commit(); await wb.commit();
    record({ id: "xlsx-large", file: "generated/xlsx-large-500k-rows.xlsx", format: "xlsx", category: "large", producer, licence, generated: true,
      expect: { result: "open", sheets: ["Large"], text: ["Region"] }, rules: SAFE_RULES,
      notes: "Performance target: first sheet opens without exhausting memory. The preview currently shows the first 10,000 rows with a notice." });
  }
}
